# Generated by Django 5.2.3 on 2025-06-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('subtitle', models.CharField(max_length=100)),
                ('decsription', models.CharField(max_length=1000)),
            ],
        ),
    ]
