databases:
  - name: shopback-staging-db
    databaseName: shopback_staging
    user: shopback_staging_user

services:
  - type: web
    name: shopback-staging
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: bash start.sh
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: APP_ENV
        value: staging
      - key: DJANGO_DEBUG
        value: "False"
      - key: CACHE_ENABLED
        value: "True"
      - key: CACHE_REDIS_URL
        sync: false
      - key: FRONTEND_BASE_URL
        value: https://flexdrive-front.vercel.app
      - key: DJANGO_ALLOWED_HOSTS
        value: flexdrive-back.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://flexdrive-front.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://flexdrive-front.vercel.app
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: shopback-staging-db
          property: connectionString
