# Generated by Django 5.2.3 on 2025-06-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Team_member',
        ),
    ]
