# Generated by Django 5.2.3 on 2025-06-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_employee_team_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_member',
            new_name='Team',
        ),
    ]
