# Generated by Django 6.0 on 2026-03-15 11:43

from django.db import migrations, models


def migrate_completed_to_delivered(apps, schema_editor):
    Order = apps.get_model("commerce", "Order")
    Order.objects.filter(status="completed").update(status="delivered")


def noop_reverse(apps, schema_editor):
    # Keep reverse migration non-destructive for already transitioned tracking data.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_order_email'),
    ]

    operations = [
        migrations.RunPython(migrate_completed_to_delivered, noop_reverse),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20),
        ),
    ]
