# Generated by Django 6.0 on 2026-03-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_guest_wishlist_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='primary_image_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
