# Generated by Django 6.0 on 2026-04-07 09:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_product_seo_fields'),
        ('commerce', '0008_cartitem_unit_price_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_source',
            field=models.CharField(choices=[('cart', 'Cart'), ('buy_now', 'Buy now')], db_index=True, default='cart', max_length=20),
        ),
        migrations.CreateModel(
            name='BuyNowSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_now_sessions', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_now_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('guest_token__isnull', True), ('user__isnull', False)), models.Q(('guest_token__isnull', False), ('user__isnull', True)), _connector='OR'), name='commerce_buy_now_session_requires_single_owner'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='commerce_one_buy_now_session_per_user'), models.UniqueConstraint(condition=models.Q(('guest_token__isnull', False)), fields=('guest_token',), name='commerce_one_buy_now_session_per_guest')],
            },
        ),
    ]
