# Generated by Django 6.0 on 2026-06-18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0013_remove_order_company_legal_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stockreservation",
            name="commerce_stock_reservation_requires_single_owner",
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        guest_token__isnull=True,
                        user__isnull=False,
                    ),
                    models.Q(
                        guest_token__isnull=False,
                        user__isnull=True,
                    ),
                    models.Q(
                        guest_token__isnull=True,
                        status__in=("completed", "expired", "released"),
                        user__isnull=True,
                    ),
                    _connector="OR",
                ),
                name="commerce_stock_reservation_requires_single_owner",
            ),
        ),
    ]
