# Generated by Django 6.0 on 2026-06-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0014_relax_historical_stock_reservation_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.UUIDField(
                        db_index=True,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("cart", "Cart"), ("buy_now", "Buy now")],
                        max_length=20,
                    ),
                ),
                ("owner_fingerprint", models.CharField(max_length=64)),
                ("request_fingerprint", models.CharField(max_length=64)),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkout_attempt",
                        to="commerce.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
