# Generated by Django 6.0 on 2026-06-18 14:26

from django.db import migrations, models


def validate_provider_transaction_ids(apps, schema_editor):
    PaymentTransaction = apps.get_model("commerce", "PaymentTransaction")
    duplicates = list(
        PaymentTransaction.objects.exclude(provider_transaction_id="")
        .values("provider", "provider_transaction_id")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)[:5]
    )
    if duplicates:
        duplicate_labels = ", ".join(
            f"{row['provider']}:{row['provider_transaction_id']}"
            for row in duplicates
        )
        raise RuntimeError(
            "Duplicate provider transaction IDs must be resolved before "
            f"applying this migration: {duplicate_labels}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_checkoutattempt'),
    ]

    operations = [
        migrations.RunPython(
            validate_provider_transaction_ids,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_id', ''), _negated=True), fields=('provider', 'provider_transaction_id'), name='commerce_unique_provider_transaction_id'),
        ),
    ]
