# Generated by Django 6.0 on 2026-06-18 14:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def validate_commerce_numeric_values(apps, schema_editor):
    checks = [
        ("BuyNowSession", "unit_price_snapshot", "lt", 0),
        ("BuyNowSession", "quantity", "lt", 1),
        ("CartItem", "unit_price_snapshot", "lt", 0),
        ("CartItem", "quantity", "lt", 1),
        ("Order", "subtotal", "lt", 0),
        ("Order", "total", "lt", 0),
        ("OrderItem", "unit_price", "lt", 0),
        ("OrderItem", "line_total", "lt", 0),
        ("OrderItem", "quantity", "lt", 1),
        ("PaymentTransaction", "amount", "lt", 0),
        ("StockReservationItem", "unit_price_snapshot", "lt", 0),
        ("StockReservationItem", "quantity", "lt", 1),
    ]
    violations = []
    for model_name, field_name, lookup, minimum in checks:
        model = apps.get_model("commerce", model_name)
        queryset = model.objects.filter(
            **{f"{field_name}__{lookup}": minimum}
        )
        if queryset.exists():
            violations.append(
                f"{model_name}.{field_name}: {queryset.count()}"
            )

    if violations:
        raise RuntimeError(
            "Invalid commerce numeric data must be corrected before applying "
            f"this migration ({'; '.join(violations)})."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_category_catalog_category_markup_range_and_more'),
        ('commerce', '0016_unique_provider_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            validate_commerce_numeric_values,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='buynowsession',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_snapshot__gte', Decimal('0.00'))), name='commerce_buy_now_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='buynowsession',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='commerce_buy_now_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_snapshot__gte', Decimal('0.00'))), name='commerce_cart_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='commerce_cart_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', Decimal('0.00'))), name='commerce_order_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', Decimal('0.00'))), name='commerce_order_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', Decimal('0.00'))), name='commerce_order_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', Decimal('0.00'))), name='commerce_order_item_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='commerce_order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='commerce_payment_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_snapshot__gte', Decimal('0.00'))), name='commerce_reservation_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='commerce_reservation_item_quantity_positive'),
        ),
    ]
