# Generated by Django 6.0 on 2026-06-22

import uuid
from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def populate_payment_tokens_and_validate_history(apps, schema_editor):
    PaymentTransaction = apps.get_model("commerce", "PaymentTransaction")

    invalid_target_ids = list(
        PaymentTransaction.objects.filter(
            order__isnull=True,
            reservation__isnull=True,
        ).values_list("id", flat=True)[:10]
    )
    if invalid_target_ids:
        raise RuntimeError(
            "Payment transactions without an order or reservation must be "
            f"resolved before this migration: {invalid_target_ids}"
        )

    invalid_amount_ids = list(
        PaymentTransaction.objects.filter(
            amount__lte=Decimal("0.00"),
        ).values_list("id", flat=True)[:10]
    )
    if invalid_amount_ids:
        raise RuntimeError(
            "Non-positive payment transaction amounts must be resolved before "
            f"this migration: {invalid_amount_ids}"
        )

    for payment_transaction in PaymentTransaction.objects.filter(
        models.Q(public_token__isnull=True)
        | models.Q(idempotency_key__isnull=True)
    ).iterator():
        updates = {}
        if payment_transaction.public_token is None:
            updates["public_token"] = uuid.uuid4()
        if payment_transaction.idempotency_key is None:
            updates["idempotency_key"] = uuid.uuid4()
        PaymentTransaction.objects.filter(pk=payment_transaction.pk).update(
            **updates
        )


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0020_order_marketing_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="public_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="idempotency_key",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="provider_order_id",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="provider_action_id",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="checkout_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="redirect_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("mock", "Mock"),
                    ("manual", "Manual"),
                    ("bog", "Bank of Georgia"),
                ],
                db_index=True,
                default="mock",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01"))
                ],
            ),
        ),
        migrations.RemoveConstraint(
            model_name="paymenttransaction",
            name="commerce_payment_amount_nonnegative",
        ),
        migrations.RunPython(
            populate_payment_tokens_and_validate_history,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="public_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="idempotency_key",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(order__isnull=False)
                    | models.Q(reservation__isnull=False)
                ),
                name="commerce_payment_requires_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                condition=~models.Q(provider_action_id=""),
                fields=("provider", "provider_action_id"),
                name="commerce_unique_provider_action_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(amount__gt=Decimal("0.00")),
                name="commerce_payment_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["provider", "provider_order_id"],
                name="commerce_pay_prov_order_idx",
            ),
        ),
    ]
