# Generated by Django 6.0 on 2026-07-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_payment_transaction_safety_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasywayRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_internal_delivery', models.BooleanField(db_index=True, default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name', 'external_id'),
                'indexes': [models.Index(fields=['is_active', 'name'], name='commerce_ea_is_acti_10bb40_idx')],
            },
        ),
        migrations.CreateModel(
            name='EasywayCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='commerce.easywayregion')),
            ],
            options={
                'ordering': ('region__name', 'name', 'external_id'),
                'indexes': [models.Index(fields=['region', 'is_active', 'name'], name='commerce_ea_region__cb29ab_idx')],
            },
        ),
    ]
