# Generated by Django 6.0 on 2026-07-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0023_order_delivery_quote_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='easyway_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='easyway_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='easyway_order_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='easyway_shipment_state',
            field=models.CharField(choices=[('not_sent', 'Not sent'), ('submitting', 'Sending - verify before retry'), ('created', 'Created'), ('failed', 'Rejected - retry allowed'), ('unknown', 'Unknown - manual check required')], db_index=True, default='not_sent', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='easyway_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
