# Generated by Django 6.0 on 2026-07-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0024_order_easyway_last_attempt_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='easyway_shipment_state',
            field=models.CharField(choices=[('not_sent', 'Not sent'), ('submitting', 'Sending - verify before retry'), ('created', 'Created'), ('failed', 'Rejected - retry allowed'), ('unknown', 'Unknown - manual check required'), ('cancelling', 'Cancelling - verify before retry'), ('cancelled', 'Cancelled'), ('cancel_failed', 'Cancellation rejected'), ('cancel_unknown', 'Cancellation unknown - manual check required')], db_index=True, default='not_sent', max_length=20),
        ),
    ]
