# Generated by Django 6.0.8 on 2026-09-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0029_easyway_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasywaySyncReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='დაწყება')),
                ('finished_at', models.DateTimeField(verbose_name='დასრულება')),
                ('source', models.CharField(choices=[('scheduled', 'პერიოდული შემოწმება'), ('manual', 'ხელით შემოწმება')], max_length=16, verbose_name='წყარო')),
                ('status', models.CharField(choices=[('success', 'წარმატებული'), ('review', 'საჭიროა ყურადღება'), ('failed', 'შეცდომა')], db_index=True, max_length=16, verbose_name='შედეგი')),
                ('summary', models.TextField(verbose_name='შეჯამება')),
                ('details', models.JSONField(default=dict, editable=False)),
            ],
            options={
                'verbose_name': 'EasyWay სინქრონიზაციის ანგარიში',
                'verbose_name_plural': 'EasyWay სინქრონიზაციის ანგარიშები',
                'ordering': ('-started_at', '-pk'),
            },
        ),
    ]
