# Generated by Django 6.0.8 on 2026-09-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0030_easyway_sync_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='reconciliation_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reconciliation_issue',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reconciliation_lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reconciliation_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reconciliation_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
