# Generated by Django 6.0.8 on 2026-09-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0031_payment_reconciliation_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='internal_sku',
            field=models.CharField(blank=True, max_length=64, verbose_name='FlexDrive SKU at checkout'),
        ),
    ]
