# Generated by Django 6.0.8 on 2026-09-29 08:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_individual_product_pricing'),
        ('commerce', '0032_orderitem_internal_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='purchase_cost_recorded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='შესაძენი ფასის დაფიქსირების დრო'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchase_cost_source',
            field=models.CharField(blank=True, choices=[('catalog_supplier_price', 'მომწოდებლის ფასი კატალოგიდან'), ('unavailable', 'მონაცემი არ არის')], db_default='', default='', editable=False, max_length=32, verbose_name='შესაძენი ფასის წყარო'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchase_unit_gross',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='შესაძენი ერთეულის ფასი დღგ-ით (ისტორიული)'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_unit_gross__isnull', True), ('purchase_unit_gross__gte', 0), _connector='OR'), name='commerce_item_purchase_nonnegative'),
        ),
    ]
