# Generated by Django 6.0.8 on 2026-09-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0033_orderitem_purchase_cost_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at', '-id'), 'permissions': (('view_accounting_report', 'Can view and export accounting reports'),)},
        ),
    ]
