# Generated by Django 6.0.8 on 2026-10-07 14:26

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_individual_product_pricing'),
        ('commerce', '0034_accounting_report_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disposition', models.CharField(choices=[('not_purchased', 'მომწოდებლისგან ჯერ არ შემიძენია'), ('on_hand', 'უკვე შეძენილია და ჩემთანაა'), ('from_customer', 'მომხმარებლისგან უკან ველოდები')], max_length=24, verbose_name='ნივთების მდგომარეობა')),
                ('receipt_status', models.CharField(choices=[('not_required', 'ნივთის მიღება საჭირო არ არის'), ('awaiting', 'ნივთის დაბრუნებას ველოდებით'), ('received', 'მიღებულია და შემოწმებულია')], db_index=True, default='awaiting', max_length=24, verbose_name='მიღების მდგომარეობა')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='მიღებისა და შემოწმების დრო')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='return_case', to='commerce.order', verbose_name='შეკვეთა')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_order_returns', to=settings.AUTH_USER_MODEL, verbose_name='მიიღო და შეამოწმა')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_order_returns', to=settings.AUTH_USER_MODEL, verbose_name='დააფიქსირა')),
            ],
            options={
                'verbose_name': 'დაბრუნება',
                'verbose_name_plural': 'დასაბრუნებელი ნივთები',
                'ordering': ('-created_at', '-pk'),
                'default_permissions': ('view', 'change'),
            },
        ),
        migrations.CreateModel(
            name='OrderReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='მოსალოდნელი რაოდენობა')),
                ('saleable_quantity', models.PositiveIntegerField(default=0, verbose_name='გასაყიდად ვარგისი')),
                ('unsaleable_quantity', models.PositiveIntegerField(default=0, verbose_name='გასაყიდად უვარგისი')),
                ('inspected_at', models.DateTimeField(blank=True, null=True, verbose_name='შემოწმების დრო')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='return_line', to='commerce.orderitem', verbose_name='შეკვეთის პროდუქტი')),
                ('return_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='commerce.orderreturn', verbose_name='დაბრუნება')),
            ],
            options={
                'verbose_name': 'დაბრუნების პროდუქტი',
                'verbose_name_plural': 'დაბრუნების პროდუქტები',
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='OwnedStockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='პარტიის ნომერი')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='მიღებული რაოდენობა')),
                ('purchase_unit_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ისტორიული შესყიდვის ფასი დღგ-ით')),
                ('purchase_cost_recorded_at', models.DateTimeField(blank=True, null=True, verbose_name='ფასის დაფიქსირების დრო')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_stock_lots', to='catalog.product', verbose_name='პროდუქტი')),
                ('return_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='commerce.orderreturnline', verbose_name='მიღების წყარო')),
            ],
            options={
                'verbose_name': 'FlexDrive-ის მარაგის მიღება',
                'verbose_name_plural': 'FlexDrive-ის მარაგი',
                'ordering': ('created_at', 'pk'),
                'default_permissions': ('view',),
            },
        ),
        migrations.AddConstraint(
            model_name='orderreturn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('disposition', 'not_purchased'), ('receipt_status', 'not_required'), ('received_at__isnull', True)), models.Q(('disposition', 'from_customer'), ('receipt_status', 'awaiting'), ('received_at__isnull', True)), models.Q(('disposition__in', ['on_hand', 'from_customer']), ('receipt_status', 'received'), ('received_at__isnull', False)), _connector='OR'), name='commerce_return_receipt_state'),
        ),
        migrations.AddConstraint(
            model_name='orderreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('expected_quantity__gte', 1)), name='commerce_return_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderreturnline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('inspected_at__isnull', True), ('saleable_quantity', 0), ('unsaleable_quantity', 0)), models.Q(('inspected_at__isnull', False), ('expected_quantity', django.db.models.expressions.CombinedExpression(models.F('saleable_quantity'), '+', models.F('unsaleable_quantity')))), _connector='OR'), name='commerce_return_full_inspection'),
        ),
        migrations.AddConstraint(
            model_name='ownedstocklot',
            constraint=models.UniqueConstraint(fields=('return_line', 'batch_number'), name='commerce_owned_lot_receipt_unique'),
        ),
        migrations.AddConstraint(
            model_name='ownedstocklot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='commerce_owned_lot_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='ownedstocklot',
            constraint=models.CheckConstraint(condition=models.Q(('batch_number__gte', 1)), name='commerce_owned_lot_batch_positive'),
        ),
        migrations.AddConstraint(
            model_name='ownedstocklot',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_unit_gross__isnull', True), ('purchase_unit_gross__gte', 0), _connector='OR'), name='commerce_owned_lot_cost_nonnegative'),
        ),
    ]
