# Generated by Django 6.0.8 on 2026-10-07 14:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def initialize_owned_balances(apps, schema_editor):
    # Earlier foundation receipt lots may exist in a test environment. Derive
    # only the new balance; never reinterpret external/supplier quantities.
    alias = schema_editor.connection.alias
    lots = apps.get_model("commerce", "OwnedStockLot").objects.using(alias)
    products = apps.get_model("catalog", "Product").objects.using(alias)
    for row in lots.values("product_id").annotate(total=models.Sum("quantity")):
        products.filter(pk=row["product_id"]).update(owned_stock_qty=row["total"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_owned_stock_allocation'),
        ('commerce', '0035_return_inventory_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedstocklot',
            name='source_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_receipts', to='commerce.ownedstocklot', verbose_name='წინა მიღების პარტია'),
        ),
        migrations.CreateModel(
            name='OrderItemInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_quantity', models.PositiveIntegerField(verbose_name='გარე მარაგიდან რაოდენობა')),
                ('external_source', models.CharField(max_length=32, verbose_name='გარე მარაგის წყარო')),
                ('purchase_total_gross', models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='ისტორიული შესყიდვის ჯამი დღგ-ით')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='commerce.orderitem')),
            ],
            options={
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='OwnedStockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='გაყიდული რაოდენობა')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='გაუქმებისას აღდგენის დრო')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='commerce.orderiteminventory')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='commerce.ownedstocklot')),
            ],
            options={
                'default_permissions': ('view',),
            },
        ),
        migrations.AddConstraint(
            model_name='orderiteminventory',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_total_gross__isnull', True), ('purchase_total_gross__gte', 0), _connector='OR'), name='commerce_inventory_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='ownedstockallocation',
            constraint=models.UniqueConstraint(fields=('inventory', 'lot'), name='commerce_inventory_lot_unique'),
        ),
        migrations.AddConstraint(
            model_name='ownedstockallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='commerce_allocation_qty_positive'),
        ),
        migrations.RunPython(initialize_owned_balances, migrations.RunPython.noop),
    ]
