# Generated by Django 5.2.3 on 2025-06-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_content_component_content_contentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
