# Generated by Django 5.2.3 on 2025-07-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_component_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
