# Generated by Django 5.2.3 on 2025-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_order_page_parent_page_show_in_menu_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
