# Generated by Django 5.2.3 on 2025-07-04 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contentitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='singlePageRoute',
            field=models.ForeignKey(blank=True, help_text='აირჩიე გვერდი, რომლის ქვეშაც უნდა ჩაჯდეს single view URL.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.page'),
        ),
    ]
