# Generated by Django 5.2.3 on 2025-07-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contentitem_singlepageroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
