# Generated by Django 5.2.3 on 2025-07-06 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_contentitem_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='pages.content'),
        ),
    ]
