# Generated by Django 5.2.3 on 2025-07-07 15:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_component_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='editor',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
