# Generated by Django 5.2.3 on 2025-07-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_contentitem_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
