# Generated by Django 5.2.3 on 2025-07-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_component_created_at_component_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='image',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='image',
        ),
        migrations.AddField(
            model_name='component',
            name='image_desktop',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='component',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='image_desktop',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
