# Generated by Django 6.0 on 2026-02-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_page_seo_description_page_seo_image_page_seo_noindex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/'),
        ),
    ]
