# Generated by Django 6.0 on 2026-02-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_alter_page_seo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="image_tablet",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="image_tablet",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
