# Generated by Django 6.0 on 2026-02-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_component_image_tablet_contentitem_image_tablet'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='icon_svg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
