# Generated by Django 6.0 on 2026-03-02 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_contentitem_icon_svg_contentitem_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.CharField(blank=True, max_length=320)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=1)),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('author_role', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags. Example: safety, maintenance, tips', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_item', models.OneToOneField(limit_choices_to={'content__name': 'bloglist'}, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='pages.contentitem')),
            ],
            options={
                'ordering': ('-published_at', '-id'),
                'indexes': [models.Index(fields=['status', 'published_at'], name='pages_blogp_status_1a57c9_idx'), models.Index(fields=['is_featured', 'published_at'], name='pages_blogp_is_feat_8de580_idx')],
            },
        ),
    ]

