# Generated by Django 6.0 on 2026-03-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_desktop',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/covers/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/covers/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_tablet',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/covers/'),
        ),
    ]
