# Generated by Django 6.0 on 2026-03-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("pages", "0018_blogpost_cover_image_desktop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="catalog_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page_content_items",
                to="catalog.category",
            ),
        ),
    ]
