# Generated by Django 6.0 on 2026-03-10 00:00

from django.db import migrations


SECTION_TITLE = "რა პრობლემას გიგვარებს AutoMate"
SECTION_SUBTITLE = (
    "ავტომობილის ყოველდღიური გამოყენება ბევრ პატარა შეუსაბამობას ქმნის. "
    "ჩვენ ვარჩევთ ნივთებს, რომლებიც მათ ნამდვილად გვარობს."
)
COMPONENT_TYPE_NAME = "ProblemSolving"
CONTENT_NAME = "problem_solving_cards"

CARD_DEFINITIONS = (
    {
        "position": 1,
        "title": "არეული სალონი",
        "description": (
            "ორგანიზატორები და პრაქტიკული აქსესუარები, "
            "რომ მანქანაში ყველაფერი თავის ადგილზე იყოს."
        ),
        "content_type": "problem_card",
        "category_slug": "interior",
        "category_name": "Interior",
        "category_sort_order": 1,
        "icon_svg": """
<svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="5" y="8" width="20" height="14" rx="3" stroke="#ff6b35" stroke-width="1.8" fill="none"/>
  <rect x="9" y="12" width="5" height="6" rx="1.5" fill="#ff6b35" opacity=".25"/>
  <rect x="16" y="12" width="5" height="3" rx="1.5" fill="#ff6b35" opacity=".25"/>
  <rect x="16" y="17" width="5" height="1.5" rx=".75" fill="#ff6b35" opacity=".4"/>
  <path d="M5 22 L5 25 M25 22 L25 25" stroke="#ff6b35" stroke-width="1.8" stroke-linecap="round"/>
  <path d="M9 8 L9 5 M21 8 L21 5" stroke="#ff6b35" stroke-width="1.5" stroke-linecap="round" opacity=".5"/>
</svg>
""".strip(),
    },
    {
        "position": 2,
        "title": "მეტი კომფორტი გზაზე",
        "description": (
            "ყოველდღიური მგზავრობისთვის შერჩეული ნივთები, რომლებიც მართვას "
            "და გადაადგილებას უფრო კომფორტულს ხდის."
        ),
        "content_type": "problem_card",
        "category_slug": "comfort",
        "category_name": "Comfort",
        "category_sort_order": 4,
        "icon_svg": """
<svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
  <circle cx="15" cy="15" r="10" stroke="#ff6b35" stroke-width="1.8" fill="none"/>
  <circle cx="15" cy="15" r="3.5" stroke="#ff6b35" stroke-width="1.8" fill="none"/>
  <path d="M15 11.5 L15 5" stroke="#ff6b35" stroke-width="1.8" stroke-linecap="round"/>
  <path d="M11.5 18 L6.5 21" stroke="#ff6b35" stroke-width="1.8" stroke-linecap="round"/>
  <path d="M18.5 18 L23.5 21" stroke="#ff6b35" stroke-width="1.8" stroke-linecap="round"/>
  <circle cx="22" cy="8" r="1.2" fill="#ff6b35" opacity=".5"/>
  <circle cx="25" cy="11" r=".8" fill="#ff6b35" opacity=".3"/>
</svg>
""".strip(),
    },
    {
        "position": 3,
        "title": "უსაფრთხოება გზაზე",
        "description": (
            "Dash cam-ები, holder-ები და სხვა საჭირო აქსესუარები "
            "მეტი კონტროლისა და სიმშვიდისთვის."
        ),
        "content_type": "problem_card",
        "category_slug": "safety",
        "category_name": "Safety",
        "category_sort_order": 5,
        "icon_svg": """
<svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M15 4 L24 7.5 L24 15 C24 20 19.5 24 15 26 C10.5 24 6 20 6 15 L6 7.5 Z" stroke="#ff6b35" stroke-width="1.8" fill="none" stroke-linejoin="round"/>
  <path d="M11 15 L13.5 17.5 L19 12" stroke="#ff6b35" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M15 4 L24 7.5 L24 15 C24 20 19.5 24 15 26" fill="#ff6b35" opacity=".05"/>
</svg>
""".strip(),
    },
    {
        "position": 4,
        "title": "ავტომობილის მოვლა",
        "description": "სისუფთავისა და ყოველდღიური მოვლისთვის საჭირო პრაქტიკული პროდუქტები.",
        "content_type": "problem_card",
        "category_slug": "exterior",
        "category_name": "Exterior",
        "category_sort_order": 2,
        "icon_svg": """
<svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M15 5 L16.5 10 L21.5 8 L18 12.5 L23 14 L18 15.5 L21.5 20 L16.5 17.5 L15 23 L13.5 17.5 L8.5 20 L12 15.5 L7 14 L12 12.5 L8.5 8 L13.5 10 Z" stroke="#ff6b35" stroke-width="1.6" fill="none" stroke-linejoin="round"/>
  <circle cx="15" cy="14" r="3" fill="#ff6b35" opacity=".2"/>
  <circle cx="5" cy="7" r="1.2" fill="#ff6b35" opacity=".4"/>
  <circle cx="25" cy="22" r=".9" fill="#ff6b35" opacity=".3"/>
  <circle cx="24" cy="6" r=".7" fill="#ff6b35" opacity=".5"/>
</svg>
""".strip(),
    },
)


def _ensure_category(Category, slug, name, sort_order):
    category, created = Category.objects.get_or_create(
        slug=slug,
        defaults={
            "name": name,
            "sort_order": sort_order,
            "is_active": True,
        },
    )

    update_fields = []
    if category.name != name:
        category.name = name
        update_fields.append("name")
    if category.sort_order != sort_order:
        category.sort_order = sort_order
        update_fields.append("sort_order")
    if not category.is_active:
        category.is_active = True
        update_fields.append("is_active")

    if update_fields:
        category.save(update_fields=update_fields)

    return category


def seed_problem_solving_component(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    Component = apps.get_model("pages", "Component")
    ComponentType = apps.get_model("pages", "ComponentType")
    Content = apps.get_model("pages", "Content")
    ContentItem = apps.get_model("pages", "ContentItem")
    Page = apps.get_model("pages", "Page")

    main_page, _ = Page.objects.get_or_create(
        slug="main",
        defaults={
            "name": "მთავარი",
            "show_in_menu": True,
            "order": 0,
        },
    )

    component_type, _ = ComponentType.objects.get_or_create(name=COMPONENT_TYPE_NAME)
    content, _ = Content.objects.get_or_create(name=CONTENT_NAME)

    component = (
        Component.objects
        .filter(page=main_page, component_type=component_type)
        .order_by("id")
        .first()
    )
    if component is None:
        component = Component.objects.create(
            page=main_page,
            component_type=component_type,
            content=content,
            title=SECTION_TITLE,
            subtitle=SECTION_SUBTITLE,
            button_text=None,
            enabled=True,
        )
    else:
        update_fields = []
        if component.content_id != content.id:
            component.content = content
            update_fields.append("content")
        if component.title != SECTION_TITLE:
            component.title = SECTION_TITLE
            update_fields.append("title")
        if component.subtitle != SECTION_SUBTITLE:
            component.subtitle = SECTION_SUBTITLE
            update_fields.append("subtitle")
        if component.button_text is not None:
            component.button_text = None
            update_fields.append("button_text")
        if not component.enabled:
            component.enabled = True
            update_fields.append("enabled")
        if update_fields:
            component.save(update_fields=update_fields)

    for card in CARD_DEFINITIONS:
        category = _ensure_category(
            Category,
            card["category_slug"],
            card["category_name"],
            card["category_sort_order"],
        )
        ContentItem.objects.update_or_create(
            content=content,
            position=card["position"],
            defaults={
                "title": card["title"],
                "description": card["description"],
                "content_type": card["content_type"],
                "icon_svg": card["icon_svg"],
                "catalog_category_id": category.id,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("pages", "0019_contentitem_catalog_category"),
    ]

    operations = [
        migrations.RunPython(seed_problem_solving_component, migrations.RunPython.noop),
    ]
