# Generated by Django 6.0 on 2026-03-10 00:00

from django.db import migrations, models


HOME_COMPONENT_ORDER = {
    "HeroSection": 10,
    "ProblemSolving": 20,
    "FeaturedProducts": 30,
    "HowItWorks": 40,
    "BlogSection": 50,
}


def populate_component_positions(apps, schema_editor):
    Component = apps.get_model("pages", "Component")
    Page = apps.get_model("pages", "Page")

    for page in Page.objects.all().order_by("id"):
        components = list(
            Component.objects
            .filter(page_id=page.id)
            .select_related("component_type")
            .order_by("id")
        )
        next_position = 10

        if page.slug == "main":
            assigned_ids = set()
            for component_name, position in HOME_COMPONENT_ORDER.items():
                matched = next(
                    (
                        component for component in components
                        if component.id not in assigned_ids
                        and getattr(component.component_type, "name", "") == component_name
                    ),
                    None,
                )
                if matched is None:
                    continue
                Component.objects.filter(pk=matched.pk).update(position=position)
                assigned_ids.add(matched.id)
                next_position = max(next_position, position + 10)

            remaining_components = [
                component for component in components if component.id not in assigned_ids
            ]
        else:
            remaining_components = components

        for component in remaining_components:
            Component.objects.filter(pk=component.pk).update(position=next_position)
            next_position += 10


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0020_seed_problem_solving_component"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="position",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(populate_component_positions, migrations.RunPython.noop),
    ]
