# Generated by Django 6.0 on 2026-03-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_remove_contact_hero_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_original',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/covers/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='teaser_image_desktop',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/teasers/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='teaser_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/teasers/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='teaser_image_original',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/teasers/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='teaser_image_tablet',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/teasers/'),
        ),
    ]
