# Generated by Django 6.0 on 2026-04-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_cleanup_problem_solving_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='brand_name',
            field=models.CharField(default='FlexDrive', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='FlexDrive', max_length=255),
        ),
    ]
