# Generated by Django 6.0 on 2026-06-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0069_replace_placeholder_legal_contact_info'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['page', 'enabled', 'position'], name='pages_comp_page_en_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['content', 'position'], name='pages_ci_content_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['content', 'content_type', 'slug'], name='pages_ci_content_type_slug_idx'),
        ),
    ]
