# Generated by Django 5.2.3 on 2025-07-10 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
