# Generated by Django 5.2.3 on 2025-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
