# Generated by Django 5.2.3 on 2026-04-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auth_token_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
