from django.urls import path

from .views import (
    BuyNowCardPaymentStartAPIView,
    BogPaymentCallbackAPIView,
    BuyNowCheckoutAPIView,
    BuyNowSessionAPIView,
    BuyNowSessionConfirmationAPIView,
    CartAPIView,
    CartCardPaymentStartAPIView,
    CartItemDetailAPIView,
    CartItemListAPIView,
    CartPriceConfirmationAPIView,
    OrderCheckoutAPIView,
    OrderSummaryAPIView,
    OrderLookupAPIView,
    OwnedOrderListAPIView,
    OwnedOrderDetailAPIView,
    WishlistAPIView,
    WishlistItemDetailAPIView,
    WishlistItemListAPIView,
    CardPaymentStatusAPIView,
    CardPaymentAvailabilityAPIView,
    DeliveryCityListAPIView,
    DeliveryQuoteAPIView,
    DeliveryRegionListAPIView,
)

urlpatterns = [
    path(
        "delivery/regions/",
        DeliveryRegionListAPIView.as_view(),
        name="commerce-delivery-region-list",
    ),
    path(
        "delivery/regions/<int:region_id>/cities/",
        DeliveryCityListAPIView.as_view(),
        name="commerce-delivery-city-list",
    ),
    path(
        "delivery/quote/",
        DeliveryQuoteAPIView.as_view(),
        name="commerce-delivery-quote",
    ),
    path("buy-now/session/", BuyNowSessionAPIView.as_view(), name="commerce-buy-now-session"),
    path(
        "buy-now/session/confirm/",
        BuyNowSessionConfirmationAPIView.as_view(),
        name="commerce-buy-now-session-confirm",
    ),
    path("buy-now/checkout/", BuyNowCheckoutAPIView.as_view(), name="commerce-buy-now-checkout"),
    path(
        "payments/card/buy-now/start/",
        BuyNowCardPaymentStartAPIView.as_view(),
        name="commerce-buy-now-card-payment-start",
    ),
    path("cart/", CartAPIView.as_view(), name="commerce-cart"),
    path("cart/confirm-prices/", CartPriceConfirmationAPIView.as_view(), name="commerce-cart-confirm-prices"),
    path("cart/items/", CartItemListAPIView.as_view(), name="commerce-cart-item-list"),
    path("cart/items/<int:pk>/", CartItemDetailAPIView.as_view(), name="commerce-cart-item-detail"),
    path("wishlist/", WishlistAPIView.as_view(), name="commerce-wishlist"),
    path("wishlist/items/", WishlistItemListAPIView.as_view(), name="commerce-wishlist-item-list"),
    path("wishlist/items/<int:product_id>/", WishlistItemDetailAPIView.as_view(), name="commerce-wishlist-item-detail"),
    path("orders/checkout/", OrderCheckoutAPIView.as_view(), name="commerce-order-checkout"),
    path(
        "payments/card/availability/",
        CardPaymentAvailabilityAPIView.as_view(),
        name="commerce-card-payment-availability",
    ),
    path(
        "payments/card/cart/start/",
        CartCardPaymentStartAPIView.as_view(),
        name="commerce-cart-card-payment-start",
    ),
    path(
        "payments/card/<uuid:public_token>/",
        CardPaymentStatusAPIView.as_view(),
        name="commerce-card-payment-status",
    ),
    path(
        "payments/bog/callback/",
        BogPaymentCallbackAPIView.as_view(),
        name="commerce-bog-payment-callback",
    ),
    path("orders/lookup/", OrderLookupAPIView.as_view(), name="commerce-order-lookup"),
    path("orders/", OwnedOrderListAPIView.as_view(), name="commerce-order-list"),
    path("orders/<uuid:public_token>/detail/", OwnedOrderDetailAPIView.as_view(), name="commerce-order-detail"),
    path("orders/<uuid:public_token>/", OrderSummaryAPIView.as_view(), name="commerce-order-summary"),
]
