"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from urllib.parse import parse_qs, unquote, urlparse
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
load_dotenv()


def _parse_bool_env(name, default=False):
    raw_value = os.getenv(name)
    if raw_value is None:
        return default

    return raw_value.strip().lower() in {"1", "true", "yes", "on"}


def _parse_csv_env(name, default=""):
    raw_value = os.getenv(name, default)
    return [item.strip().rstrip("/") for item in raw_value.split(",") if item.strip()]


def _parse_int_env(name, default):
    raw_value = os.getenv(name)
    if raw_value is None:
        return default

    try:
        return int(raw_value.strip())
    except ValueError:
        return default


def _parse_samesite_env(name, default="Lax"):
    raw_value = os.getenv(name, default)
    normalized = raw_value.strip().lower()
    mapping = {
        "lax": "Lax",
        "strict": "Strict",
        "none": "None",
    }
    return mapping.get(normalized, default)


def _dedupe(values):
    result = []
    seen = set()

    for value in values:
        normalized = str(value).strip()
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        result.append(normalized)

    return result


def _sqlite_database_config(base_dir):
    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': base_dir / 'db.sqlite3',
    }


def _database_config_from_env(base_dir):
    database_url = os.getenv("DATABASE_URL", "").strip()
    if not database_url:
        return _sqlite_database_config(base_dir)

    parsed = urlparse(database_url)
    scheme = parsed.scheme.lower().split("+", 1)[0]

    if scheme in {"postgres", "postgresql", "pgsql"}:
        config = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parsed.path.lstrip("/")),
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or ""),
            "CONN_MAX_AGE": _parse_int_env("DATABASE_CONN_MAX_AGE", 60),
        }
        query_params = parse_qs(parsed.query)
        if query_params.get("sslmode"):
            config["OPTIONS"] = {"sslmode": query_params["sslmode"][0]}
        return config

    if scheme in {"sqlite", "sqlite3"}:
        path = unquote(parsed.path or "")
        if path.startswith("/") and len(path) >= 3 and path[2] == ":":
            path = path[1:]
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": path.lstrip("/") or (base_dir / "db.sqlite3"),
        }

    raise ValueError(f"Unsupported DATABASE_URL scheme: {parsed.scheme}")



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
USE_CLOUDINARY_MEDIA = _parse_bool_env("USE_CLOUDINARY_MEDIA", False)
CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME", "").strip()
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY", "").strip()
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET", "").strip()

if USE_CLOUDINARY_MEDIA:
    missing_cloudinary_settings = [
        name
        for name, value in (
            ("CLOUDINARY_CLOUD_NAME", CLOUDINARY_CLOUD_NAME),
            ("CLOUDINARY_API_KEY", CLOUDINARY_API_KEY),
            ("CLOUDINARY_API_SECRET", CLOUDINARY_API_SECRET),
        )
        if not value
    ]
    if missing_cloudinary_settings:
        missing_list = ", ".join(missing_cloudinary_settings)
        raise ImproperlyConfigured(
            f"USE_CLOUDINARY_MEDIA=True requires these settings: {missing_list}"
        )

STORAGES = {
    "default": (
        {"BACKEND": "common.storage_backends.CloudinaryMediaStorage"}
        if USE_CLOUDINARY_MEDIA
        else {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": MEDIA_ROOT,
                "base_url": MEDIA_URL,
            },
        }
    ),
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure--_bfns!nr^c#*c+ivlubs!ekah4ppv8yn24hflx56=b1wg4x_+",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _parse_bool_env("DJANGO_DEBUG", True)

COOKIE_SECURE_BY_DEFAULT = not DEBUG
COOKIE_SAMESITE_BY_DEFAULT = "Lax"

SESSION_COOKIE_SECURE = _parse_bool_env("SESSION_COOKIE_SECURE", COOKIE_SECURE_BY_DEFAULT)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = _parse_samesite_env("SESSION_COOKIE_SAMESITE", COOKIE_SAMESITE_BY_DEFAULT)
SESSION_COOKIE_DOMAIN = os.getenv("SESSION_COOKIE_DOMAIN") or None

CSRF_COOKIE_SECURE = _parse_bool_env("CSRF_COOKIE_SECURE", COOKIE_SECURE_BY_DEFAULT)
CSRF_COOKIE_HTTPONLY = False  # CSRF cookie áƒ£áƒœáƒ“áƒ áƒ˜áƒ§áƒáƒ¡ áƒ¬áƒáƒ™áƒ˜áƒ—áƒ®áƒ•áƒáƒ“áƒ˜ JS-áƒ˜áƒ—
CSRF_COOKIE_SAMESITE = _parse_samesite_env("CSRF_COOKIE_SAMESITE", COOKIE_SAMESITE_BY_DEFAULT)
CSRF_COOKIE_DOMAIN = os.getenv("CSRF_COOKIE_DOMAIN") or None

API_COOKIE_SECURE = _parse_bool_env("API_COOKIE_SECURE", COOKIE_SECURE_BY_DEFAULT)
API_COOKIE_SAMESITE = _parse_samesite_env("API_COOKIE_SAMESITE", COOKIE_SAMESITE_BY_DEFAULT)
API_COOKIE_DOMAIN = os.getenv("API_COOKIE_DOMAIN") or None
API_COOKIE_PATH = os.getenv("API_COOKIE_PATH", "/").strip() or "/"
CART_EMPTY_TTL_SECONDS = _parse_int_env("CART_EMPTY_TTL_SECONDS", 60 * 60 * 24)
CART_GUEST_TTL_SECONDS = _parse_int_env("CART_GUEST_TTL_SECONDS", 60 * 60 * 24 * 30)
CART_USER_TTL_SECONDS = _parse_int_env("CART_USER_TTL_SECONDS", 60 * 60 * 24 * 60)
BUY_NOW_SESSION_TTL_SECONDS = _parse_int_env("BUY_NOW_SESSION_TTL_SECONDS", 60 * 60 * 2)
STOCK_RESERVATION_TTL_SECONDS = _parse_int_env("STOCK_RESERVATION_TTL_SECONDS", 60 * 15)

SECURE_SSL_REDIRECT = _parse_bool_env("SECURE_SSL_REDIRECT", not DEBUG)
USE_X_FORWARDED_HOST = _parse_bool_env("USE_X_FORWARDED_HOST", not DEBUG)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = _parse_int_env("SECURE_HSTS_SECONDS", 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _parse_bool_env("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = _parse_bool_env("SECURE_HSTS_PRELOAD", False)

FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "https://localhost:3000").strip().rstrip("/")
default_allowed_hosts = ["localhost", "127.0.0.1"]
render_external_hostname = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
if render_external_hostname:
    default_allowed_hosts.append(render_external_hostname)
default_frontend_origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://localhost:3000",
    "https://127.0.0.1:3000",
]

if FRONTEND_BASE_URL:
    default_frontend_origins.append(FRONTEND_BASE_URL)

ALLOWED_HOSTS = _dedupe(default_allowed_hosts + _parse_csv_env("DJANGO_ALLOWED_HOSTS"))
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = _dedupe(
    default_frontend_origins + _parse_csv_env("CORS_ALLOWED_ORIGINS")
)
CSRF_TRUSTED_ORIGINS = _dedupe(
    default_frontend_origins + _parse_csv_env("CSRF_TRUSTED_ORIGINS")
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalog.apps.CatalogConfig',
    'employees',
    'projects',
    'pages.apps.PagesConfig',
    'accounts',
    'commerce',
    'ckeditor',
    'corsheaders',  
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',



]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'common.middleware.NoStorePrivateApiMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': _database_config_from_env(BASE_DIR)
}

CACHE_ENABLED = _parse_bool_env("CACHE_ENABLED", False)
CACHE_PREFIX = os.getenv("CACHE_PREFIX", "shopback").strip() or "shopback"
CACHE_REDIS_URL = os.getenv("CACHE_REDIS_URL", "").strip()

CACHE_TTL_MENU = _parse_int_env("CACHE_TTL_MENU", 60 * 60)
CACHE_TTL_FOOTER = _parse_int_env("CACHE_TTL_FOOTER", 60 * 60)
CACHE_TTL_SITE_SETTINGS = _parse_int_env("CACHE_TTL_SITE_SETTINGS", 60 * 60)
CACHE_TTL_PAGE_CONTENT = _parse_int_env("CACHE_TTL_PAGE_CONTENT", 15 * 60)
CACHE_TTL_BLOG_LIST = _parse_int_env("CACHE_TTL_BLOG_LIST", 5 * 60)
CACHE_TTL_CATALOG_CATEGORIES = _parse_int_env("CACHE_TTL_CATALOG_CATEGORIES", 10 * 60)

if CACHE_ENABLED and not CACHE_REDIS_URL:
    raise ImproperlyConfigured(
        "CACHE_ENABLED=true requires CACHE_REDIS_URL to be set."
    )

if CACHE_ENABLED:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": CACHE_REDIS_URL,
            "KEY_PREFIX": CACHE_PREFIX,
            "TIMEOUT": None,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
            "TIMEOUT": None,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
    }
}


# CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'accounts.CustomUser'


EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp-relay.brevo.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _parse_bool_env('EMAIL_USE_TLS', True)
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '10'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '91c063001@smtp-brevo.com')
EMAIL_HOST_PASSWORD = os.getenv("BREVO_SMTP_KEY")
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'kenchoshvili.alexander1@gmail.com')
BREVO_API_KEY = os.getenv("BREVO_API_KEY", "").strip()
BREVO_API_TIMEOUT = int(os.getenv("BREVO_API_TIMEOUT", "10"))


# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         # áƒáƒ£áƒªáƒ˜áƒšáƒ”áƒ‘áƒšáƒáƒ“ áƒ›áƒ˜áƒ£áƒ—áƒ˜áƒ—áƒ” áƒ¨áƒ”áƒœáƒ˜ áƒáƒžáƒšáƒ˜áƒ™áƒáƒªáƒ˜áƒ˜áƒ¡ áƒ¡áƒáƒ®áƒ”áƒšáƒ˜ (áƒ—áƒ£ áƒáƒžáƒšáƒ˜áƒ™áƒáƒªáƒ˜áƒáƒ¡ 'accounts' áƒ°áƒ¥áƒ•áƒ˜áƒ)
#         'accounts.authenticate.CustomJWTAuthentication', 
#     ),
#     'DEFAULT_PERMISSION_CLASSES': [
#         # 'rest_framework.permissions.IsAuthenticated',
#         'rest_framework.permissions.AllowAny'
#     ],
# }
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authenticate.CustomAuthentication', # áƒ”áƒ¡ áƒ£áƒœáƒ“áƒ áƒ˜áƒ§áƒáƒ¡ áƒžáƒ˜áƒ áƒ•áƒ”áƒšáƒ˜!
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny', # áƒ áƒáƒ’áƒáƒ áƒª áƒ¨áƒ”áƒ•áƒ—áƒáƒœáƒ®áƒ›áƒ“áƒ˜áƒ—, áƒ“áƒ áƒáƒ”áƒ‘áƒ˜áƒ— áƒ¦áƒ˜áƒáƒ
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/min',
        'user': '120/min',
        'login': '5/min',
        'register': '10/min',
        'checkout': '10/min',
        'google_auth': '10/min',
        'order_lookup': '10/min',
        'password_reset': '5/min',
        'activation_resend': '5/hour',
    }
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7), 
    'ROTATE_REFRESH_TOKENS': True,    # <--- áƒ“áƒáƒáƒ›áƒáƒ¢áƒ” áƒ”áƒ¡
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_COOKIE': 'access_token',  # áƒ”áƒ¡ áƒ£áƒœáƒ“áƒ áƒ”áƒ›áƒ—áƒ®áƒ•áƒ”áƒáƒ“áƒ”áƒ¡ views.py-áƒ¨áƒ˜ key-áƒ¡ áƒ¡áƒáƒ®áƒ”áƒšáƒ¡
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_PATH': API_COOKIE_PATH,
    'AUTH_COOKIE_SAMESITE': API_COOKIE_SAMESITE,
    'AUTH_COOKIE_SECURE': API_COOKIE_SECURE,
}

GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID", "").strip()
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", "").strip()
GOOGLE_OAUTH_REDIRECT_URI = os.getenv("GOOGLE_OAUTH_REDIRECT_URI", "").strip()
GOOGLE_AUTH_CLOCK_SKEW_SECONDS = _parse_int_env("GOOGLE_AUTH_CLOCK_SKEW_SECONDS", 30)
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY')
RECAPTCHA_MIN_SCORE = 0.5
RECAPTCHA_TIMEOUT_SECONDS = 5
RECAPTCHA_ALLOWED_HOSTNAMES = [
    host.strip()
    for host in os.getenv("RECAPTCHA_ALLOWED_HOSTNAMES", "localhost,127.0.0.1").split(",")
    if host.strip()
]
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     )
# }





