
'use strict';
const icons={
 overview:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
 sales:'<path d="M3 7h18l-1.5 13h-15L3 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/>',
 finance:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 9h18m-5 5h2M7 15h3"/>',
 users:'<circle cx="9" cy="7" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2m1-16a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 4v2"/>',
 marketing:'<path d="m4 10 13-5v14L4 14v-4Zm0 0H2v4h2m4 2 1 5h3l-2-5m10-7 2-1m-2 7 2 1"/>',
 operations:'<path d="M4 6h16v14H4zM3 6l3-3h12l3 3M9 10h6m-3 0v6"/>',
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
 arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',
 layers:'<path d="m12 3 10 5-10 5L2 8l10-5Zm-9 9 9 5 9-5M3 16l9 5 9-5"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18m-13 5h2m4 0h2"/>',
 download:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v4h16v-4"/>',
 bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9m-12 9h12m-9 4h6"/>',
 info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>',
 pulse:'<path d="M2 12h5l3-7 4 14 3-7h5"/>',
 close:'<path d="m6 6 12 12M6 18 18 6"/>',
 menu:'<path d="M4 6h16M4 12h16M4 18h16"/>'
};
const icon=(name)=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.info}</svg>`;
const escapeHTML=(value)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const format=(value,digits=0)=>new Intl.NumberFormat('ka-GE',{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value);
const money=(value,digits=0)=>`${format(value,digits)} ₾`;
const percent=(value,digits=1)=>`${format(value,digits)}%`;
const monthly={
 september:{name:'სექტემბერი',previousName:'აგვისტო',month:9,days:30,revenue:18460,previousRevenue:15120,orders:64,previousOrders:56,units:92,previousUnits:81,profit:5240,previousProfit:4490,refund:740,refundOrders:3,visits:3240,previousVisits:2880,views:4890,cart:420,checkout:148,spend:1260,previousSpend:1180,impressions:86400,clicks:1830,likes:286,comments:42,followers:128,previousFollowers:103},
 august:{name:'აგვისტო',previousName:'ივლისი',month:8,days:31,revenue:15120,previousRevenue:13980,orders:56,previousOrders:51,units:81,previousUnits:75,profit:4490,previousProfit:3980,refund:480,refundOrders:2,visits:2880,previousVisits:2640,views:4270,cart:365,checkout:124,spend:1180,previousSpend:1120,impressions:78200,clicks:1620,likes:241,comments:35,followers:103,previousFollowers:94},
 july:{name:'ივლისი',previousName:'ივნისი',month:7,days:31,revenue:13980,previousRevenue:14420,orders:51,previousOrders:54,units:75,previousUnits:78,profit:3980,previousProfit:4180,refund:320,refundOrders:1,visits:2640,previousVisits:2750,views:4010,cart:341,checkout:117,spend:1120,previousSpend:1150,impressions:72600,clicks:1490,likes:218,comments:31,followers:94,previousFollowers:98}
};
const views={
 overview:{label:'მიმოხილვა',title:'ბიზნესის პულსი',eyebrow:'მთლიანი სურათი, ერთ სივრცეში',description:'რა შეიცვალა, რა მუშაობს და რას უნდა მიაქციო ყურადღება.'},
 sales:{label:'გაყიდვები',title:'გაყიდვების სურათი',eyebrow:'შეკვეთიდან — შედეგამდე',description:'გადახდილი შეკვეთები, გაყიდული ნაწილები და ცვლილება წინა თვესთან.'},
 finance:{label:'ფინანსები',title:'ფინანსები გარკვევით',eyebrow:'მიღებული თანხა და პროდუქტის მოგება',description:'გადახდები და დაბრუნებები ცალ-ცალკე, გასაგები განმარტებებით.'},
 users:{label:'მომხმარებლები',title:'რა აინტერესებთ მომხმარებლებს',eyebrow:'შემოსვლა, ინტერესი, შეძენა',description:'საიდან მოდიან, რას ეძებენ და სად წყდება შეძენის გზა.'},
 marketing:{label:'მარკეტინგი',title:'მარკეტინგის შედეგები',eyebrow:'რეკლამა და სოციალური აქტივობა',description:'ხარჯი, კლიკები და კონტენტის გამოხმაურება — ცალსახა წყაროებით.'},
 operations:{label:'ოპერაციები',title:'რას სჭირდება ყურადღება',eyebrow:'ბიზნესის ყოველდღიური მდგომარეობა',description:'შეკვეთები, დაბრუნებები და პროცესები, რომლებიც გადამოწმებას მოითხოვს.'}
};
let state={view:'overview',period:'september',chart:'revenue'};
const el=(id)=>document.getElementById(id);
const data=()=>monthly[state.period];
const comparisonName=()=>{const n=data().previousName;return n.endsWith("ი")?n.slice(0,-1)+"თან":n+"სთან";};
const growth=(current,previous)=>previous===0?null:(current-previous)/previous*100;
function growthLabel(current,previous){const value=growth(current,previous);if(value===null)return '<span class="growth neutral">შედარება არ არის</span>';return `<span class="growth ${value<0?'down':''}">${value>=0?'↗':'↘'} ${percent(Math.abs(value))}</span>`;}
const source=(name)=>`<span class="source-label">${name} · მაგალითი</span>`;
function metric(label,value,previous,current,sourceName,help){return `<div class="metric"><div class="metric-label">${label}${help?`<button class="help" data-action="${help}" aria-label="${label}: განმარტება">?</button>`:''}</div><div class="metric-value num">${value}</div><div class="metric-foot">${growthLabel(current,previous)}<span>${comparisonName()} შედარებით</span></div>${source(sourceName)}</div>`;}
function financialMetrics(){const d=data();return `<section class="metrics" aria-label="მთავარი მაჩვენებლები">${metric('მიღებული თანხა',`${format(d.revenue)}<span class="currency">₾</span>`,d.previousRevenue,d.revenue,'ჩვენი ბაზა','revenue')}${metric('გადახდილი შეკვეთები',format(d.orders),d.previousOrders,d.orders,'ჩვენი ბაზა','orders')}${metric('გაყიდული ერთეულები',format(d.units),d.previousUnits,d.units,'ჩვენი ბაზა','units')}${metric('პროდუქტის მოგება',`${format(d.profit)}<span class="currency">₾</span>`,d.previousProfit,d.profit,'ფინანსური ანგარიში','profit')}</section>`;}
function splitTotal(total,days,offset=0){const weights=Array.from({length:days},(_,i)=>32+((i*17+offset*11)%42)+Math.round(18*Math.sin(i/3+offset))+i*.8);const sum=weights.reduce((a,b)=>a+b,0);let used=0;return weights.map((w,i)=>{const n=i===days-1?total-used:Math.round(total*w/sum);used+=n;return n;});}
function trendPanel(){const d=data(),orders=state.chart==='orders',total=orders?d.orders:d.revenue;return `<section class="panel"><div class="panel-head"><div><h2>${orders?'შეკვეთების':'გაყიდვების'} დინამიკა</h2><p class="panel-subtitle">დღიური შედეგი და წინა თვის შედარება</p></div><div class="segmented" aria-label="გრაფიკის მაჩვენებელი"><button data-chart="revenue" class="${!orders?'active':''}" aria-pressed="${!orders}">თანხა</button><button data-chart="orders" class="${orders?'active':''}" aria-pressed="${orders}">შეკვეთები</button></div></div><div class="chart-summary"><strong class="num">${orders?format(total):money(total)}</strong>${growthLabel(total,orders?d.previousOrders:d.previousRevenue)}<span>სრული თვე</span></div><div class="legend"><span><i></i>${d.name}</span><span><i class="previous"></i>${d.previousName}</span></div><div class="chart-wrap" id="chartWrap"><svg id="trendChart" class="trend-chart" viewBox="0 0 700 220" role="img" aria-label="${d.name}ს დღიური ${orders?'შეკვეთების':'მიღებული თანხის'} საილუსტრაციო გრაფიკი"></svg><div id="chartTooltip" class="chart-tooltip" hidden></div></div><div class="chart-caption"><span><strong>პერიოდი:</strong> 1–${d.days} ${d.name}, 2026</span>${source('ჩვენი ბაზა')}</div></section>`;}
function drawTrend(){const svg=el('trendChart');if(!svg)return;const d=data(),orders=state.chart==='orders',a=splitTotal(orders?d.orders:d.revenue,d.days,d.month),b=splitTotal(orders?d.previousOrders:d.previousRevenue,d.days,d.month-1),max=Math.ceil(Math.max(...a,...b)/ (orders?1:200))*(orders?1:200);const chartWidth=Math.max(300,Math.round(svg.getBoundingClientRect().width));svg.setAttribute("viewBox",`0 0 ${chartWidth} 220`);const left=49,right=chartWidth-12,top=16,bottom=183;const x=i=>left+i/(d.days-1)*(right-left),y=n=>bottom-(n/max)*(bottom-top);const points=values=>values.map((n,i)=>`${x(i).toFixed(2)},${y(n).toFixed(2)}`).join(' ');let html='';for(let i=0;i<=3;i++){const n=max*i/3;html+=`<line class="chart-grid" x1="${left}" y1="${y(n)}" x2="${right}" y2="${y(n)}"/><text class="axis" x="${left-10}" y="${y(n)+3}" text-anchor="end">${format(n)}</text>`;}html+=`<polygon class="trend-area" points="${left},${bottom} ${points(a)} ${right},${bottom}"/><polyline class="trend-previous" points="${points(b)}"/><polyline class="trend-current" points="${points(a)}"/>`;[0,Math.round(d.days*.23),Math.round(d.days*.46),Math.round(d.days*.7),d.days-1].forEach(i=>{html+=`<text class="axis" x="${x(i)}" y="210" text-anchor="middle">${String(i+1).padStart(2,'0')} ${d.name.slice(0,3)}.</text>`;});a.forEach((n,i)=>{html+=`<circle class="chart-point" cx="${x(i)}" cy="${y(n)}" r="6" tabindex="0" data-day="${i+1}" data-value="${n}" aria-label="${i+1} ${d.name}: ${orders?`${n} შეკვეთა`:money(n)}"><title>${i+1} ${d.name}: ${orders?`${n} შეკვეთა`:money(n)}</title></circle>`;});svg.innerHTML=html;svg.querySelectorAll('[data-day]').forEach(point=>{const show=()=>{const tip=el('chartTooltip');tip.textContent=`${point.dataset.day} ${d.name} · ${orders?point.dataset.value+' შეკვეთა':money(Number(point.dataset.value))}`;tip.hidden=false;const rect=point.getBoundingClientRect(),wrap=el('chartWrap').getBoundingClientRect();tip.style.left=Math.min(Math.max(8,rect.left-wrap.left-48),wrap.width-tip.offsetWidth-8)+'px';tip.style.top=Math.max(3,rect.top-wrap.top-50)+'px';};point.addEventListener('mouseenter',show);point.addEventListener('focus',show);point.addEventListener('mouseleave',()=>el('chartTooltip').hidden=true);point.addEventListener('blur',()=>el('chartTooltip').hidden=true);});}
function insightPanel(){const d=data(),change=growth(d.revenue,d.previousRevenue),up=change>=0;return `<aside class="insight"><div class="insight-tag">${icon('pulse')}თვის მოკლე მიმოხილვა</div><h2>გაყიდვები<br><em>${up?'მზარდია':'შემცირებულია'}.</em></h2><p>${d.name}ში მიღებული თანხა ${comparisonName()} შედარებით <em>${percent(Math.abs(change))}-ით ${up?'გაიზარდა':'შემცირდა'}</em>. გადახდილია ${d.orders} შეკვეთა; საშუალო თანხაა ${money(d.revenue/d.orders,2)}.</p><div class="insight-separator"></div><div class="insight-note">${icon('search')}<span>ძებნის მაგალითებში „ფორესტერის სარკე“ ხშირად გვხვდება. ნახე, რა შედეგს იღებს მომხმარებელი.</span></div><button class="insight-link" data-view="users">მომხმარებლების ინტერესები ${icon('arrow')}</button></aside>`;}
function products(){const d=data(),q=d.units===92?[24,21,18,16,13]:d.units===81?[22,18,16,14,11]:[20,17,15,13,10],prices=[100,110,190,250,300];return ['სარკის ქვედა ხუფი (LH)','წინა სამუხრუჭე ხუნდები','წინა ფარი (RH)','წინა ბამპერი','რადიატორი'].map((name,i)=>({name,sku:['FD-05-0042','FD-03-0018','FD-01-0106','FD-02-0084','FD-06-0023'][i],qty:q[i],revenue:q[i]*prices[i]}));}
function productPanel(full=false){const rows=products();if(full)return `<section class="panel"><div class="panel-head"><div><h2>გაყიდვები პროდუქტების მიხედვით</h2><p class="panel-subtitle">საილუსტრაციო ჩამონათვალი · კომპანია SKU</p></div><input class="search-input" id="productFilter" placeholder="სახელი ან FD კოდი" aria-label="პროდუქტების გაფილტვრა"></div><div class="table-wrap"><table class="data-table"><thead><tr><th>პროდუქტი</th><th>ერთეული</th><th>პროდუქტის გაყიდვის თანხა</th><th>მთლიანი რაოდენობის წილი</th></tr></thead><tbody id="productRows">${productTableRows(rows)}</tbody></table></div><div class="panel-footer">თანხა მოიცავს მხოლოდ პროდუქტის ფასს; შეკვეთის მიწოდების თანხა აქ არ შედის.</div></section>`;return `<section class="panel"><div class="panel-head"><div><h2>ყველაზე გაყიდვადი ნაწილები</h2><p class="panel-subtitle">პოპულარული პროდუქტები რაოდენობის მიხედვით</p></div><button class="text-link" data-view="sales">ყველა ${icon('arrow')}</button></div><div class="rows">${rows.slice(0,4).map((r,i)=>`<div class="list-row"><span class="rank num">0${i+1}</span><div class="row-body"><div class="row-title">${r.name}</div><div class="row-meta">${r.sku}</div></div><div class="row-num num">${r.qty}<small>ერთეული</small></div></div>`).join('')}</div><div class="panel-footer">${source('დადასტურებული გაყიდვები')}</div></section>`;}
function productTableRows(rows){return rows.length?rows.map(r=>`<tr><td><strong>${r.name}</strong><div class="row-meta">${r.sku}</div></td><td class="num">${r.qty}</td><td class="num">${money(r.revenue)}</td><td class="num">${percent(r.qty/data().units*100)}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">ამ სახელით ან კოდით მაგალითი ვერ მოიძებნა.</td></tr>';}
function searches(){const mult=data().visits/3240;return [['ფორესტერის სარკე',128,8],['სამუხრუჭე ხუნდები',96,24],['პრიუსის ფარი',74,11],['ფორესტერი 2020 ხუფი',42,0],['ბამპერი ტოიოტა',38,7]].map(([term,count,results])=>({term,count:Math.round(count*mult),results}));}
function searchPanel(full=false){return `<section class="panel"><div class="panel-head"><div><h2>${full?'ძებნის სიტყვები და შედეგები':'რას ეძებენ ყველაზე ხშირად'}</h2><p class="panel-subtitle">დასრულებული ძებნები, აკრეფილი ასოების ნაცვლად</p></div>${!full?`<button class="text-link" data-view="users">დეტალები ${icon('arrow')}</button>`:''}</div><div class="rows">${searches().slice(0,full?5:4).map(r=>`<div class="list-row"><span class="search-code">${icon('search')}</span><div class="row-body"><div class="row-title">${r.term}</div><div class="row-meta">${r.results===0?'<span style="color:var(--warning)">შედეგი ვერ მოიძებნა</span>':r.results+' პროდუქტი შედეგებში'}</div></div><div class="row-num num">${r.count}<small>ძებნა</small></div></div>`).join('')}</div><div class="panel-footer">${source('საიტის ძებნის აღრიცხვა')}</div></section>`;}
function trafficPanel(){const d=data();return `<section class="panel"><div class="panel-head"><div><h2>საიდან მოდიან</h2><p class="panel-subtitle">ვიზიტების განაწილება წყაროების მიხედვით</p></div></div><div class="bar-list">${[['Google · ორგანული',42],['Facebook / Instagram',31],['პირდაპირი შემოსვლა',19],['სხვა წყაროები',8]].map(([name,p])=>`<div class="bar-row"><div class="bar-label"><span>${name}</span><strong class="num">${percent(p,0)}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${p}%"></div></div></div>`).join('')}</div><div class="panel-footer">${source('Google Analytics')}<span>${format(d.visits)} ვიზიტი · უცნობი წყარო არ მიეწერება რეკლამას</span></div></section>`;}
function funnelPanel(){const d=data();return `<section class="panel"><div class="panel-head"><div><h2>შეძენის გზა</h2><p class="panel-subtitle">საფეხურები საილუსტრაციო მაგალითში</p></div><button class="help" data-action="funnel" aria-label="შეძენის გზის განმარტება">?</button></div><div class="funnel">${[['პროდუქტის ნახვა',d.views],['კალათაში დამატება',d.cart],['გადახდის დაწყება',d.checkout],['დადასტურებული შეძენა',d.orders]].map(([label,n],i)=>`<div class="funnel-row"><div><p>${label}</p><div class="funnel-bar"><i style="width:${n/d.views*100}%"></i></div></div><div style="text-align:right"><strong class="num">${format(n)}</strong></div></div>`).join('')}</div><div class="panel-footer">${source('საიტის მოვლენები და გადახდები')}</div></section>`;}
function alertsPanel(){return `<section class="panel"><div class="panel-head"><div><h2>საყურადღებო საკითხები</h2><p class="panel-subtitle">შეტყობინებების ვიზუალური მაგალითები</p></div><span class="chip warn">2 საკითხი</span></div><div class="alert-list"><div class="alert-row"><span class="alert-dot"></span><div><p>მოთხოვნადი საძიებო სიტყვა შედეგის გარეშე</p><small>„ფორესტერი 2020 ხუფი“ · გადამოწმების მაგალითი</small></div></div><div class="alert-row"><span class="alert-dot"></span><div><p>დაბრუნების მიღება დასადასტურებელია</p><small>1 საილუსტრაციო შეკვეთა ელოდება შემოწმებას</small></div></div></div><div class="panel-footer"><button class="text-link" data-view="operations">ოპერაციების ნახვა ${icon('arrow')}</button></div></section>`;}
function overview(){return financialMetrics()+`<div class="upper-grid">${trendPanel()}${insightPanel()}</div><div class="grid-two">${productPanel()}${searchPanel()}</div><div class="bottom-grid">${trafficPanel()}${funnelPanel()}${alertsPanel()}</div>`;}
function sales(){const d=data();return financialMetrics()+`<div class="upper-grid">${trendPanel()}<section class="panel"><div class="explain-block"><h3>შეკვეთა რიცხვებში</h3><p>საშუალო შეკვეთის თანხა გვიჩვენებს, რამდენს იხდის მომხმარებელი თითო დასრულებულ შეკვეთაზე.</p><div class="formula"><strong class="num">${money(d.revenue/d.orders,2)}</strong><p>${money(d.revenue)} ÷ ${d.orders} გადახდილი შეკვეთა</p></div><div class="formula"><strong class="num">${format(d.units/d.orders,2)}</strong><p>ერთეული საშუალოდ თითო შეკვეთაში</p></div></div></section></div><div style="margin-bottom:24px">${productPanel(true)}</div><div class="callout"><strong>როგორ ითვლება გაყიდვა?</strong> ახალი ან გადაუხდელი შეკვეთა გაყიდვად არ ჩაითვლება. დაბრუნებები ცალკე აღირიცხება; ფინანსებში ჩანს მათი გამოკლებით მიღებული თანხაც.</div>`;}
function finance(){const d=data();return financialMetrics()+`<div class="grid-two"><section class="panel"><div class="panel-head"><div><h2>თანხების მოძრაობა</h2><p class="panel-subtitle">დადასტურებული გადახდები და დაბრუნებები</p></div></div><div class="explain-block"><div class="finance-row"><span>მიღებული თანხა</span><span class="num">${money(d.revenue)}</span></div><div class="finance-row"><span>დაბრუნებული თანხა</span><span class="num" style="color:var(--error)">− ${money(d.refund)}</span></div><div class="finance-row"><span>მიღებული თანხა დაბრუნებების შემდეგ</span><span class="num">${money(d.revenue-d.refund)}</span></div></div><div class="panel-footer">${source('გადახდის დადასტურებული ჩანაწერები')}</div></section><section class="panel"><div class="explain-block"><span class="chip">მაჩვენებლის განმარტება</span><h3 style="margin-top:18px">პროდუქტის მოგება ≠ კომპანიის წმინდა მოგება</h3><p>ეს მაჩვენებელი ეყრდნობა პროდუქტის გაყიდვის ფასსა და შენახულ თვითღირებულებას, დღგ-ის გარეშე. რეკლამა, ხელფასი და სხვა ბიზნესხარჯები სრულად აქ არ გამოიქვითება.</p><p style="margin-top:12px">უცნობი თვითღირებულება ნულად არ ჩაითვლება. ასეთ შემთხვევაში მოგებაც არასრულად იქნება მონიშნული.</p><button class="text-link" style="margin-top:14px" data-action="profit">განმარტების გახსნა ${icon('arrow')}</button></div></section></div><section class="panel" style="margin-bottom:24px"><div class="panel-head"><div><h2>ფინანსური მოვლენების მაგალითები</h2><p class="panel-subtitle">ეს არ არის რეალური შეკვეთების ჩამონათვალი</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>ჩანაწერი</th><th>თარიღი</th><th>მოვლენა</th><th>თანხა</th></tr></thead><tbody><tr><td><strong>DEMO-SALE-01</strong></td><td>28 ${d.name}</td><td><span class="chip">გადახდილი</span></td><td class="num">410 ₾</td></tr><tr><td><strong>DEMO-SALE-02</strong></td><td>27 ${d.name}</td><td><span class="chip">გადახდილი</span></td><td class="num">280 ₾</td></tr><tr><td><strong>DEMO-RETURN-01</strong></td><td>24 ${d.name}</td><td><span class="chip warn">დაბრუნებული</span></td><td class="num" style="color:var(--error)">− 180 ₾</td></tr></tbody></table></div><div class="panel-footer">რამდენიმე მაგალითი ვიზუალური შეფასებისთვის; სრული პერიოდის ჯამი ზედა ბლოკშია.</div></section>`;}
function users(){const d=data();return `<section class="metrics">${metric('საიტის ვიზიტები',format(d.visits),d.previousVisits,d.visits,'Google Analytics','visits')}${metric('პროდუქტის ნახვები',format(d.views),Math.round(d.views*.91),d.views,'საიტის მოვლენები','views')}${metric('საშუალო ვიზიტის გაყიდვის წილი',percent(d.orders/d.visits*100,2),d.previousOrders/d.previousVisits,d.orders/d.visits,'კომბინირებული მაგალითი','conversion')}${metric('ახალი გამომწერები',format(d.followers),d.previousFollowers,d.followers,'Instagram Insights','followers')}</section><div class="grid-two">${searchPanel(true)}${trafficPanel()}</div><div class="grid-two">${funnelPanel()}<section class="panel"><div class="explain-block"><span class="chip">მოთხოვნის აღმოჩენა</span><h3 style="margin-top:18px">მომხმარებელი ეძებს. ვპასუხობთ მის მოთხოვნას?</h3><p>შედეგის გარეშე დარჩენილი ძებნა შეიძლება მიუთითებდეს საჭირო ნაწილზე, საძიებო სიტყვის განსხვავებულ ფორმაზე ან თავსებადობის შეზღუდვაზე.</p><p style="margin-top:12px">პანელი გაჩვენებს კონკრეტულ სიტყვებსა და მათ სიხშირეს. მიზეზის დადგენას პროდუქტებისა და ძებნის შედეგების შემოწმება სჭირდება.</p><button class="text-link" data-action="searches" style="margin-top:18px">როგორ აღირიცხება ძებნა ${icon('arrow')}</button></div></section></div>`;}
function marketing(){const d=data();return `<section class="metrics">${metric('რეკლამის ხარჯი',`${format(d.spend)}<span class="currency">₾</span>`,d.previousSpend,d.spend,'Meta Ads','spend')}${metric('რეკლამის ჩვენებები',format(d.impressions),Math.round(d.impressions*.9),d.impressions,'Meta Ads','impressions')}${metric('ბმულზე კლიკები',format(d.clicks),Math.round(d.clicks*.89),d.clicks,'Meta Ads','clicks')}${metric('ახალი გამომწერები',format(d.followers),d.previousFollowers,d.followers,'Instagram Insights','followers')}</section><div class="callout"><strong>რეკლამის გაყიდვა და რეალური გადახდა ცალ-ცალკეა.</strong> Google-სა და Meta-ს შეუძლიათ ერთი შეკვეთა ორივემ საკუთარ კამპანიას მიაწეროს. ამიტომ მათ გაყიდვებს ერთმანეთთან არ ვაჯამებთ.</div><div class="grid-two"><section class="panel"><div class="panel-head"><div><h2>კამპანიების შედეგები</h2><p class="panel-subtitle">Meta Ads · საილუსტრაციო ანგარიში</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>კამპანია</th><th>ხარჯი</th><th>კლიკები</th><th>კლიკის ფასი</th></tr></thead><tbody>${[['კატალოგი · ავტონაწილები',.5],['Subaru · თავსებადი ნაწილები',.3],['ხელახალი დაინტერესება',.2]].map(([name,p],i)=>{const spend=i===2?d.spend-Math.round(d.spend*.5)-Math.round(d.spend*.3):Math.round(d.spend*p),clicks=i===2?d.clicks-Math.round(d.clicks*.5)-Math.round(d.clicks*.3):Math.round(d.clicks*p);return `<tr><td><strong>${name}</strong><div class="row-meta">კამპანიის მაგალითი</div></td><td class="num">${money(spend)}</td><td class="num">${format(clicks)}</td><td class="num">${money(spend/clicks,2)}</td></tr>`;}).join('')}</tbody></table></div><div class="panel-footer">სარეკლამო ხარჯი არ ნიშნავს, რომ ამ თანხით მოგება უკვე გამოითვალა.</div></section><section class="panel"><div class="panel-head"><div><h2>სოციალური გამოხმაურება</h2><p class="panel-subtitle">Instagram · ორგანული აქტივობის მაგალითი</p></div></div><div class="rows">${[['მოწონებები',d.likes,'პოსტებსა და ვიდეოებზე'],['კომენტარები',d.comments,'კონტენტზე გამოხმაურება'],['ახალი გამომწერები',d.followers,'შერჩეულ პერიოდში']].map(([name,n,desc])=>`<div class="list-row"><div class="row-body"><div class="row-title">${name}</div><div class="row-meta">${desc}</div></div><div class="row-num num">${n}</div></div>`).join('')}</div><div class="panel-footer">${source('Instagram Insights')}</div></section></div><section class="panel" style="margin-bottom:24px"><div class="explain-block"><h3>რომელ რეკლამას მოაქვს შედეგი?</h3><p>სანდო პასუხისთვის კამპანიის მონიშნული ბმულები, საიტის მოვლენები და დადასტურებული შეკვეთები შეთანხმებული წესით უნდა დავაკავშიროთ. სადაც კავშირი ვერ დგინდება, პანელი ამას ღიად მიუთითებს.</p></div></section>`;}
function operations(){return `<div class="callout"><strong>შეტყობინებების მაგალითები.</strong> ქვემოთ მოცემული მდგომარეობები შექმნილია დიზაინის შესაფასებლად; ისინი FlexDrive-ის რეალურ მიმდინარე მდგომარეობას არ აღწერს.</div><div class="grid-two">${alertsPanel()}<section class="panel"><div class="panel-head"><div><h2>ოპერაციული რიგი</h2><p class="panel-subtitle">რა ეტაპზეა სამუშაო · მაგალითი</p></div></div><div class="rows">${[['მოსამზადებელი შეკვეთები',4],['გზაში მყოფი შეკვეთები',7],['მისაღები დაბრუნებები',1],['გადახდის შესამოწმებელი ჩანაწერები',0]].map(([label,n])=>`<div class="list-row"><div class="row-title row-body">${label}</div><div class="row-num num">${n}</div></div>`).join('')}</div><div class="panel-footer">${source('ჩვენი ბექენდი')}</div></section></div><section class="panel" style="margin-bottom:24px"><div class="panel-head"><div><h2>მონაცემების განახლების მდგომარეობა</h2><p class="panel-subtitle">ნამდვილი პანელი წყაროს შეფერხებასაც გამოაჩენს</p></div></div><div class="explain-block"><div class="integration-grid">${integrationCards()}</div></div><div class="warning-copy">არცერთი წყარო ამ HTML-ში არ არის დაკავშირებული. „მონაცემი არ გვაქვს“ ყოველთვის განსხვავდება „მაჩვენებელი ნულია“-სგან.</div></section>`;}
function integrationCards(){return [['FD','FlexDrive-ის ბაზა','გადახდები, შეკვეთები, დაბრუნებები და მარაგი'],['G','Google Analytics','ვიზიტები, შემოსვლის წყაროები და საიტის მოვლენები'],['M','Meta Ads','რეკლამის ხარჯი, ჩვენებები და კლიკები'],['IG','Instagram Insights','კონტენტის ჩართულობა და გამომწერების ცვლილება']].map(([mark,name,desc])=>`<div class="integration-card"><div class="integration-symbol">${mark}</div><h3>${name}</h3><span class="chip muted">პროტოტიპში დაუკავშირებელია</span><p>${desc}</p></div>`).join('');}
const explanations={
 revenue:['მიღებული თანხა','დადასტურებული გადახდების სრული თანხა შერჩეულ პერიოდში, დაბრუნებების გამოკლებამდე. შეიძლება მოიცავდეს მიწოდებასაც. ფინანსების გვერდზე დაბრუნებები ცალკეა ნაჩვენები.'],
 orders:['გადახდილი შეკვეთები','შეკვეთები, რომლებსაც დადასტურებული წარმატებული გადახდა აქვთ. შექმნილი, მაგრამ გადაუხდელი შეკვეთები ამ მაჩვენებელში არ შედის.'],
 units:['გაყიდული ერთეულები','გადახდილ შეკვეთებში პროდუქტის რაოდენობების ჯამი. ეს არ არის შეკვეთების რაოდენობა ან განსხვავებული პროდუქტების რაოდენობა.'],
 profit:['პროდუქტის მოგება','გაყიდვის თანხასა და პროდუქტის თვითღირებულებას შორის სხვაობა, დღგ-ის გარეშე. ეს არ არის კომპანიის წმინდა მოგება: ყველა ბიზნესხარჯი აქ არ გამოიქვითება. უცნობი თვითღირებულება ნულად არ ჩაითვლება.'],
 visits:['საიტის ვიზიტები','Google Analytics-ის სესიების მაგალითი. ერთი ადამიანი შეიძლება საიტზე რამდენჯერმე შემოვიდეს და რამდენიმე ვიზიტი შექმნას. ვიზიტები არ ნიშნავს უნიკალურ ადამიანებს.'],
 views:['პროდუქტის ნახვები','პროდუქტის ნახვის მოვლენების რაოდენობა. ერთი ადამიანი ან ერთი ვიზიტი შეიძლება რამდენიმე ნახვას მოიცავდეს.'],
 conversion:['ვიზიტებისა და შეკვეთების შეფარდება','ამ პროტოტიპში: გადახდილი შეკვეთები ÷ ვიზიტები × 100. ეს მხოლოდ საილუსტრაციო შეფარდებაა. ნამდვილ კონვერსიას მომხმარებლის გზასთან დაკავშირებული, თანმიმდევრული აღრიცხვა სჭირდება.'],
 followers:['ახალი გამომწერები','შერჩეულ პერიოდში დამატებული გამომწერების მაგალითი. სრული აუდიტორიის რაოდენობა და გამომწერების წმინდა ცვლილება ცალკე მაჩვენებლებია.'],
 spend:['რეკლამის ხარჯი','სარეკლამო ანგარიშში შერჩეული პერიოდის ხარჯი. ხარჯის ზრდა თავისთავად არც კარგ შედეგს ნიშნავს და არც ცუდს; ის კლიკებსა და დადასტურებულ შედეგებს უნდა შევადაროთ.'],
 impressions:['რეკლამის ჩვენებები','რამდენჯერ გამოჩნდა რეკლამა. ერთი ადამიანი შეიძლება მას რამდენჯერმე ხედავდეს; ჩვენებები არ უდრის უნიკალურ ადამიანებს.'],
 clicks:['ბმულზე კლიკები','რეკლამის ბმულზე დაჭერის რაოდენობა. კლიკი, საიტზე წარმატებული ვიზიტი და დასრულებული შეძენა განსხვავებული მოვლენებია.'],
 funnel:['შეძენის გზა','პროტოტიპში ნაჩვენებია მოვლენების საერთო რაოდენობები. ეს ჯერ არ არის ერთმანეთთან დაკავშირებული უნიკალური მომხმარებლების funnel. ნამდვილ პანელში თითოეული საფეხურის დათვლის წესი და წყარო ცალსახად იქნება მითითებული.'],
 searches:['ძებნის აღრიცხვა','აღირიცხება დასრულებული ძებნა და მიღებული შედეგების რაოდენობა; ყოველი აკრეფილი ასო ცალკე ძებნად არ ჩაითვლება. საილუსტრაციო სიტყვები და რაოდენობები რეალური მომხმარებლების ისტორიას არ წარმოადგენს.'],
 about:['პროტოტიპის შესახებ','ეს არის ერთი დამოუკიდებელი HTML ფაილი, რომელიც FlexDrive-ის ნამდვილ დიზაინის ფერებს, ქართულ შრიფტსა და ლოგოს იყენებს. ყველა რიცხვი და მდგომარეობა დიზაინის მაგალითია. ეს ფაილი არ ასრულებს ავტორიზაციას, არ უკავშირდება ბაზას და არ აგზავნის მოთხოვნებს გარე სისტემებში. პერიოდი, ნავიგაცია, გრაფიკი, ფილტრი, ვიზუალური რეჟიმი და CSV ექსპორტი მხოლოდ ადგილობრივ მაგალითებზე მუშაობს.']
};
function showDialog(action){let title,body;if(action==='sources'){title='მონაცემების წყაროები';body='<p>ნამდვილი პანელი ამ წყაროებს ბექენდის საშუალებით დაუკავშირდება. თითოეულ მაჩვენებელს ექნება წყარო, დაფარული პერიოდი და ბოლო წარმატებული განახლების დრო.</p><div class="integration-grid">'+integrationCards()+'</div><p>ამ ფაილში წყაროები არ არის დაკავშირებული; ყველა მონაცემი საილუსტრაციოა.</p>';}else if(action==='alerts'){title='რას სჭირდება ყურადღება';body='<h3>უშედეგო ძებნა</h3><p>მაგალითი: მომხმარებელი ეძებს „ფორესტერი 2020 ხუფი“-ს და ვერ იღებს შედეგს. ეს შეიძლება მოითხოვდეს კატალოგის ან თავსებადობის გადამოწმებას.</p><h3>დაბრუნების მიღება</h3><p>მაგალითი: ერთი დაბრუნება ელოდება ნივთის მიღებასა და შემოწმებას. ამ HTML-იდან შეკვეთის ან გადახდის შეცვლა შეუძლებელია.</p>';}else{const x=explanations[action]||explanations.about;title=x[0];body=`<p>${x[1]}</p>`;}el('dialogTitle').textContent=title;el('dialogBody').innerHTML=body;el('detailsDialog').showModal();}
function render(){const v=views[state.view]||views.overview;el('breadcrumb').textContent=v.label;el('pageTitle').textContent=v.title;el('eyebrow').textContent=v.eyebrow;el('pageDescription').textContent=v.description;document.querySelectorAll('[data-nav]').forEach(n=>{const active=n.dataset.nav===state.view;n.classList.toggle('active',active);if(active)n.setAttribute('aria-current','page');else n.removeAttribute('aria-current');});el('content').innerHTML=({overview,sales,finance,users,marketing,operations})[state.view]();drawTrend();const filter=el('productFilter');if(filter)filter.addEventListener('input',()=>{const term=filter.value.trim().toLocaleLowerCase();el('productRows').innerHTML=productTableRows(products().filter(p=>(p.name+' '+p.sku).toLocaleLowerCase().includes(term)));});}
function closeMenu(){document.body.classList.remove('menu-open');el('menuButton').setAttribute('aria-expanded','false');}
function navigate(view){if(!views[view])return;if(location.hash!==`#${view}`){location.hash=view;}else{state.view=view;render();}closeMenu();window.scrollTo({top:0,behavior:'instant'});}
function readHash(){const key=location.hash.slice(1);state.view=views[key]?key:'overview';render();closeMenu();}
function toast(message){el('toast').textContent=message;el('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el('toast').hidden=true,3500);}
function applyVariant(value){document.documentElement.classList.toggle('dark',value==='dark');document.documentElement.classList.toggle('compact',value==='compact');el('variant').value=value;try{localStorage.setItem('flexdrive-preview-variant',value);}catch{}}
function exportCSV(){const d=data(),rows=[['ვიზუალური პროტოტიპი — ყველა მონაცემი საილუსტრაციოა'],['პერიოდი',`${d.name} 2026`],['მაჩვენებელი','მნიშვნელობა','წყარო'],['მიღებული თანხა',d.revenue,'ჩვენი ბაზა · მაგალითი'],['გადახდილი შეკვეთები',d.orders,'ჩვენი ბაზა · მაგალითი'],['გაყიდული ერთეულები',d.units,'ჩვენი ბაზა · მაგალითი'],['პროდუქტის მოგება დღგ-ის გარეშე',d.profit,'ფინანსური ანგარიში · მაგალითი'],['დაბრუნებული თანხა',d.refund,'ჩვენი ბაზა · მაგალითი'],['საიტის ვიზიტები',d.visits,'Google Analytics · მაგალითი'],['რეკლამის ხარჯი',d.spend,'Meta Ads · მაგალითი']];const csv='\ufeff'+rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`FlexDrive-DEMO-${state.period}-2026.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('საილუსტრაციო CSV ჩამოტვირთულია.');}
el('navigation').innerHTML=Object.entries(views).map(([key,v])=>`<a class="nav-item" href="#${key}" data-nav="${key}">${icon(key)}<span>${v.label}</span>${key==='operations'?'<span class="count">2</span>':''}</a>`).join('');
document.querySelectorAll('[data-icon]').forEach(n=>n.innerHTML=icon(n.dataset.icon));
document.addEventListener('click',event=>{const action=event.target.closest('[data-action]'),view=event.target.closest('[data-view]'),chart=event.target.closest('[data-chart]'),nav=event.target.closest('[data-nav]');if(action){showDialog(action.dataset.action);closeMenu();}if(view)navigate(view.dataset.view);if(chart){state.chart=chart.dataset.chart;render();}if(nav){event.preventDefault();navigate(nav.dataset.nav);}});
el('period').addEventListener('change',event=>{state.period=event.target.value;render();});
el('variant').addEventListener('change',event=>applyVariant(event.target.value));
el('exportButton').addEventListener('click',exportCSV);
el('closeDialog').addEventListener('click',()=>el('detailsDialog').close());
el('detailsDialog').addEventListener('click',event=>{const r=el('detailsDialog').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)el('detailsDialog').close();});
el('menuButton').addEventListener('click',()=>{const open=document.body.classList.toggle('menu-open');el('menuButton').setAttribute('aria-expanded',String(open));});
el('scrim').addEventListener('click',closeMenu);
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu();});
window.addEventListener('hashchange',readHash);
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(drawTrend,120);});
try{const saved=localStorage.getItem('flexdrive-preview-variant');if(['light','dark','compact'].includes(saved))applyVariant(saved);}catch{}
readHash();
