# Generated by Django 6.0 on 2026-05-06 08:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_from', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('year_to', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('vehicle_model__make__name', 'vehicle_model__name', 'year_from', 'year_to', 'engine__name'),
            },
        ),
        migrations.CreateModel(
            name='VehicleEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('model__make__sort_order', 'model__make__name', 'model__sort_order', 'model__name', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('make__sort_order', 'make__name', 'sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_universal_fitment',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='placement',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('rear', 'Rear'), ('upper', 'Upper'), ('lower', 'Lower'), ('inner', 'Inner'), ('outer', 'Outer')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='side',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both'), ('center', 'Center')], max_length=20),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='catalog_bra_is_acti_2e75a7_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'status'], name='catalog_pro_brand_i_f60d77_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['placement', 'side'], name='catalog_pro_placeme_79b48a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_universal_fitment', 'status'], name='catalog_pro_is_univ_3b537e_idx'),
        ),
        migrations.AddField(
            model_name='productfitment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productfitment',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_fitments', to='catalog.vehicleengine'),
        ),
        migrations.AddIndex(
            model_name='vehiclemake',
            index=models.Index(fields=['is_active', 'sort_order'], name='catalog_veh_is_acti_b36e50_idx'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='catalog.vehiclemake'),
        ),
        migrations.AddField(
            model_name='vehicleengine',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engines', to='catalog.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='productfitment',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_fitments', to='catalog.vehiclemodel'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['make', 'is_active', 'sort_order'], name='catalog_veh_make_id_62b3a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('make', 'slug'), name='catalog_unique_vehicle_model_slug_per_make'),
        ),
        migrations.AddIndex(
            model_name='vehicleengine',
            index=models.Index(fields=['model', 'is_active', 'sort_order'], name='catalog_veh_model_i_9e4b5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleengine',
            constraint=models.UniqueConstraint(fields=('model', 'slug'), name='catalog_unique_vehicle_engine_slug_per_model'),
        ),
        migrations.AddIndex(
            model_name='productfitment',
            index=models.Index(fields=['product', 'vehicle_model'], name='catalog_pro_product_9ae5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='productfitment',
            index=models.Index(fields=['vehicle_model', 'year_from', 'year_to'], name='catalog_pro_vehicle_081d55_idx'),
        ),
        migrations.AddIndex(
            model_name='productfitment',
            index=models.Index(fields=['engine', 'year_from', 'year_to'], name='catalog_pro_engine__555885_idx'),
        ),
        migrations.AddConstraint(
            model_name='productfitment',
            constraint=models.UniqueConstraint(fields=('product', 'vehicle_model', 'engine', 'year_from', 'year_to'), name='catalog_unique_product_fitment'),
        ),
        migrations.AddConstraint(
            model_name='productfitment',
            constraint=models.UniqueConstraint(condition=models.Q(('engine__isnull', True)), fields=('product', 'vehicle_model', 'year_from', 'year_to'), name='catalog_unique_generic_product_fitment'),
        ),
    ]
