# Generated by Django 6.0 on 2026-05-27 17:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productfitment_vehicleengine_vehiclemake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default markup percentage used to calculate customer prices for products in this category.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_percent_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional product-specific markup percentage. Leave empty to use the category markup.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Private supplier cost. Customer-facing price is calculated from this value and markup.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
