# Generated by Django 6.0 on 2026-06-18 10:27

import django.contrib.postgres.indexes
from django.db import migrations
from django.db.models.functions import Upper


def create_postgres_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    schema_editor.execute(
        """
        CREATE INDEX CONCURRENTLY IF NOT EXISTS catalog_product_name_trgm
        ON catalog_product USING gin (UPPER(name) gin_trgm_ops)
        """
    )
    schema_editor.execute(
        """
        CREATE INDEX CONCURRENTLY IF NOT EXISTS catalog_product_mpn_trgm
        ON catalog_product USING gin (
            UPPER(manufacturer_part_number) gin_trgm_ops
        )
        """
    )


def remove_postgres_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        "DROP INDEX CONCURRENTLY IF EXISTS catalog_product_name_trgm"
    )
    schema_editor.execute(
        "DROP INDEX CONCURRENTLY IF EXISTS catalog_product_mpn_trgm"
    )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('catalog', '0007_reorganize_catalog_categories'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_postgres_search_indexes,
                    remove_postgres_search_indexes,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='product',
                    index=django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            Upper("name"),
                            name="gin_trgm_ops",
                        ),
                        name="catalog_product_name_trgm",
                    ),
                ),
                migrations.AddIndex(
                    model_name='product',
                    index=django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            Upper("manufacturer_part_number"),
                            name="gin_trgm_ops",
                        ),
                        name="catalog_product_mpn_trgm",
                    ),
                ),
            ],
        ),
    ]
