# Generated by Django 6.0 on 2026-06-18 14:34

from decimal import Decimal
from django.db import migrations, models


def validate_catalog_numeric_values(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    Product = apps.get_model("catalog", "Product")

    invalid_checks = [
        (
            "category markup outside 0-1000",
            Category.objects.filter(
                models.Q(markup_percent__lt=0)
                | models.Q(markup_percent__gt=1000)
            ),
        ),
        ("negative product price", Product.objects.filter(price__lt=0)),
        (
            "negative supplier price",
            Product.objects.filter(supplier_price__lt=0),
        ),
        (
            "product markup outside 0-1000",
            Product.objects.filter(
                models.Q(markup_percent_override__lt=0)
                | models.Q(markup_percent_override__gt=1000)
            ),
        ),
        (
            "old price not above current price",
            Product.objects.filter(
                old_price__isnull=False,
                old_price__lte=models.F("price"),
            ),
        ),
    ]
    violations = [
        f"{label}: {queryset.count()}"
        for label, queryset in invalid_checks
        if queryset.exists()
    ]
    if violations:
        raise RuntimeError(
            "Invalid catalog numeric data must be corrected before applying "
            f"this migration ({'; '.join(violations)})."
        )


def add_catalog_numeric_constraints(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    statements = [
        """
        ALTER TABLE catalog_category
        ADD CONSTRAINT catalog_category_markup_range
        CHECK (markup_percent >= 0 AND markup_percent <= 1000)
        """,
        """
        ALTER TABLE catalog_product
        ADD CONSTRAINT catalog_product_price_nonnegative
        CHECK (price >= 0)
        """,
        """
        ALTER TABLE catalog_product
        ADD CONSTRAINT catalog_product_supplier_price_nonnegative
        CHECK (supplier_price IS NULL OR supplier_price >= 0)
        """,
        """
        ALTER TABLE catalog_product
        ADD CONSTRAINT catalog_product_markup_range
        CHECK (
            markup_percent_override IS NULL
            OR (
                markup_percent_override >= 0
                AND markup_percent_override <= 1000
            )
        )
        """,
        """
        ALTER TABLE catalog_product
        ADD CONSTRAINT catalog_product_old_price_above_price
        CHECK (old_price IS NULL OR old_price > price)
        """,
    ]
    for statement in statements:
        schema_editor.execute(statement)


def remove_catalog_numeric_constraints(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    for table_name, constraint_name in [
        ("catalog_category", "catalog_category_markup_range"),
        ("catalog_product", "catalog_product_price_nonnegative"),
        ("catalog_product", "catalog_product_supplier_price_nonnegative"),
        ("catalog_product", "catalog_product_markup_range"),
        ("catalog_product", "catalog_product_old_price_above_price"),
    ]:
        schema_editor.execute(
            f"ALTER TABLE {table_name} DROP CONSTRAINT IF EXISTS {constraint_name}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_product_search_trigram_indexes'),
    ]

    operations = [
        migrations.RunPython(
            validate_catalog_numeric_values,
            migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_catalog_numeric_constraints,
                    remove_catalog_numeric_constraints,
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='category',
                    constraint=models.CheckConstraint(condition=models.Q(('markup_percent__gte', Decimal('0.00')), ('markup_percent__lte', Decimal('1000.00'))), name='catalog_category_markup_range'),
                ),
                migrations.AddConstraint(
                    model_name='product',
                    constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.00'))), name='catalog_product_price_nonnegative'),
                ),
                migrations.AddConstraint(
                    model_name='product',
                    constraint=models.CheckConstraint(condition=models.Q(('supplier_price__isnull', True), ('supplier_price__gte', Decimal('0.00')), _connector='OR'), name='catalog_product_supplier_price_nonnegative'),
                ),
                migrations.AddConstraint(
                    model_name='product',
                    constraint=models.CheckConstraint(condition=models.Q(('markup_percent_override__isnull', True), models.Q(('markup_percent_override__gte', Decimal('0.00')), ('markup_percent_override__lte', Decimal('1000.00'))), _connector='OR'), name='catalog_product_markup_range'),
                ),
                migrations.AddConstraint(
                    model_name='product',
                    constraint=models.CheckConstraint(condition=models.Q(('old_price__isnull', True), ('old_price__gt', models.F('price')), _connector='OR'), name='catalog_product_old_price_above_price'),
                ),
            ],
        ),
    ]
