# Generated by Django 6.0 on 2026-07-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productimage_crop_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(max_length=120)),
                ('supplier_sku', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('source_name', 'supplier_sku'),
                'constraints': [models.UniqueConstraint(fields=('source_name', 'supplier_sku'), name='catalog_unique_supplier_product_block')],
            },
        ),
    ]
