# Generated by Django 6.0 on 2026-07-08 17:19

from django.db import migrations, models


def add_preserve_manual_fitment_content_column(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    table_name = schema_editor.quote_name("catalog_product")
    column_name = schema_editor.quote_name("preserve_manual_fitment_content")
    if vendor == "postgresql":
        schema_editor.execute(
            f"ALTER TABLE {table_name} ADD COLUMN {column_name} boolean NOT NULL DEFAULT false"
        )
    else:
        schema_editor.execute(
            f"ALTER TABLE {table_name} ADD COLUMN {column_name} integer NOT NULL DEFAULT 0"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_supplierproductblock'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_preserve_manual_fitment_content_column,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='preserve_manual_fitment_content',
                    field=models.BooleanField(default=False, help_text='Keep manually edited fitments, descriptions, and specs during supplier imports. Supplier price and stock will still be refreshed.'),
                ),
            ],
        ),
    ]
