# Generated by Django 6.0 on 2026-07-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_preserve_manual_fitment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_padding',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
    ]
