# Generated by Django 6.0 on 2026-07-13 19:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_productimage_ai_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_shipping_height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default packaged product height in centimeters for EasyWay quotes.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='category',
            name='default_shipping_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default packaged product length in centimeters for EasyWay quotes.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='category',
            name='default_shipping_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Default packaged product weight in kilograms for EasyWay quotes.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddField(
            model_name='category',
            name='default_shipping_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default packaged product width in centimeters for EasyWay quotes.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional packaged height override in centimeters. Leave empty to use the category default.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional packaged length override in centimeters. Leave empty to use the category default.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Optional packaged weight override in kilograms. Leave empty to use the category default.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional packaged width override in centimeters. Leave empty to use the category default.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
