# Generated by Django 6.0.8 on 2026-09-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_product_supplier_stock_tracking'),
    ]

    operations = [
        # Avoid SQLite's table rebuild attempting to recreate PostgreSQL-only
        # trigram indexes present in the historical migration state.
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL(
                'ALTER TABLE catalog_product ADD COLUMN supplier_missing boolean NOT NULL DEFAULT false',
                'ALTER TABLE catalog_product DROP COLUMN supplier_missing',
            )],
            state_operations=[migrations.AddField(
                model_name='product',
                name='supplier_missing',
                field=models.BooleanField(default=False, editable=False, help_text='Archived automatically because the product disappeared from the supplier feed.'),
            )],
        ),
    ]
