# Generated by Django 6.0.8 on 2026-09-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_product_supplier_missing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierSyncReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='დაწყება')),
                ('finished_at', models.DateTimeField(verbose_name='დასრულება')),
                ('status', models.CharField(choices=[('success', 'წარმატებული'), ('failed', 'შეცდომა')], db_index=True, max_length=16, verbose_name='შედეგი')),
                ('summary', models.TextField(verbose_name='შეჯამება')),
                ('changes', models.JSONField(default=dict, editable=False)),
            ],
            options={
                'verbose_name': 'სინქრონიზაციის ანგარიში',
                'verbose_name_plural': 'სინქრონიზაციის ანგარიშები',
                'ordering': ('-started_at', '-pk'),
            },
        ),
    ]
