# Generated by Django 6.0.8 on 2026-09-23 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_supplier_sync_report'),
    ]

    operations = [
        # Avoid SQLite table rebuilding PostgreSQL-only trigram indexes, as in 0020.
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL(
                [
                    'ALTER TABLE catalog_product ADD COLUMN internal_sku varchar(64) NULL',
                    'CREATE UNIQUE INDEX catalog_product_internal_sku_unique ON catalog_product (internal_sku)',
                ],
                [
                    'DROP INDEX catalog_product_internal_sku_unique',
                    'ALTER TABLE catalog_product DROP COLUMN internal_sku',
                ],
            )],
            state_operations=[migrations.AddField(
                model_name='product',
                name='internal_sku',
                field=models.CharField(blank=True, help_text='Customer-facing code. The existing SKU remains the supplier/integration identifier.', max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Z0-9][A-Z0-9._-]*\\Z', 'Use uppercase letters, digits, dots, underscores or hyphens.')], verbose_name='FlexDrive SKU'),
            )],
        ),
    ]
