# Generated by Django 6.0.8 on 2026-09-28 18:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class AlterMarkupPrecision(migrations.AlterField):
    # SQLite does not enforce decimal precision and needs no physical change.
    # Rebuilding its table would recreate PostgreSQL-only trigram indexes.
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor != "sqlite":
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor != "sqlite":
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_require_published_sku'),
    ]

    operations = [
        AlterMarkupPrecision(
            model_name='product',
            name='markup_percent_override',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Optional product-specific markup percentage. Leave empty to use the category markup.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))]),
        ),
    ]
