# Generated by Django 6.0.8 on 2026-09-28 18:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def set_initial_zero_markup(apps, schema_editor):
    products = apps.get_model("catalog", "Product").objects.using(schema_editor.connection.alias)
    supplier_products = products.filter(supplier_price__isnull=False)
    if supplier_products.filter(old_price__lte=models.F("supplier_price")).exists():
        raise RuntimeError("Review old_price values at or below supplier_price before the zero-markup cutover.")
    products.update(markup_percent_override=Decimal("0"))
    supplier_products.update(price=models.F("supplier_price"))


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_precise_product_markup'),
    ]

    operations = [
        # Only the Python default/help text changes; there is no persistent DB
        # default. Avoid rebuilding SQLite's PostgreSQL-indexed product table.
        migrations.SeparateDatabaseAndState(state_operations=[migrations.AlterField(
            model_name='product',
            name='markup_percent_override',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.00'), help_text='Individual product markup percentage. Empty means 0%; categories do not affect prices.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))]),
        )]),
        # One-time user-authorized pre-launch reset. Reversal cannot reconstruct
        # old pricing; take a pricing snapshot before applying on each database.
        migrations.RunPython(set_initial_zero_markup),
    ]
