# Generated by Django 6.0.8 on 2026-10-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_individual_product_pricing'),
    ]

    operations = [
        # Add in place on SQLite and PostgreSQL; rebuilding SQLite's product
        # table would try to recreate PostgreSQL-only trigram indexes.
        migrations.SeparateDatabaseAndState(database_operations=[migrations.RunSQL(
            'ALTER TABLE catalog_product ADD COLUMN owned_stock_qty integer NOT NULL DEFAULT 0 CHECK (owned_stock_qty >= 0)',
            'ALTER TABLE catalog_product DROP COLUMN owned_stock_qty',
        )], state_operations=[migrations.AddField(
            model_name='product',
            name='owned_stock_qty',
            field=models.PositiveIntegerField(db_default=0, default=0, editable=False, verbose_name='FlexDrive-ის საკუთარი ნაშთი'),
        )]),
    ]
